### ISSUE TITLE
[不具合]選択肢項目を開き、選択肢をホバーした時に選択肢の文字が白になる

### ISSUE THREAD

**Issue by junnino** [thinkingreed-inc/F-RevoCRM#106]
**概要（Overview）**
選択肢項目を開き、選択肢をホバーした時に選択肢の文字が白になる。
システム設定画面から選択肢エディタで編集画面から何もせず保存すると色が自動で白に設定され、上記の不具合が生じたと考えられます。

**再現手順（To Reproduce）**
1.カスタム項目作成から選択肢（複数）の項目を作成
2.システム設定画面→選択肢エディタから1で作成した選択肢の一つの編集画面を開く
3.何もせず保存
4.選択肢項目を作成したモジュールのレコード新規作成画面で選択肢項目を開き、先ほど編集した項目をホバーすると白に設定されているため、見えなくなる

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/78579937/112787470-89b70f80-9093-11eb-91d9-686b8ca25b19.png)
一番上の項目を上記再現手順で作成し、ホバーした結果です。

**Comment by Remicck** [comment]
@junnino 報告ありがとうございます。
ブラウザを教えてもらえますか？

**Comment by Remicck** [comment]
@junnino 
複数選択のピックリストで再現しました、こちらは白の場合、黒文字にする対応を行います。

また、本来であれば色の濃さに応じて、背景色と文字色のコントラストが最大になるように設定されるべきだと思いますので、別途Issue登録しておきます。
→ こちらはバグというよりは機能改善として。
