### ISSUE TITLE
[不具合] 個人カレンダーのページがロードし続けて止まらない

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#1124]
**概要（Overview）**
個人カレンダーおよび共有カレンダーのページがロードし続けて止まらない.
現在のmainで発生中. 
commit hash: c459ecb262b65efee6fcf085a74a7b6b00ac01ca

**再現手順（To Reproduce）**
以下のような個人カレンダーへの遷移によって発生する. 
* 右上のカレンダーアイコンをクリック
* 左バーから個人カレンダーをクリック

**スクリーンショット（Screenshots）**
![image](https://github.com/user-attachments/assets/bc79b250-389b-474d-9634-49a85aee60c8)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser: chrome
- Version: 

**その他情報（Additional context）**

**Comment by hasesho28** [comment]
同じような現象が自ローカルでも置きましたが、 #1099 で追加されているスクリプトが実行されておらず項目が無かったのが原因でした。
同様かは分かりませんがご参考までに

**Comment by K-Haruto** [comment]
コメントありがとうございます。
ご指摘の通り、7.4.1へのアップグレードを実行していないことが原因でした。
不具合ではなかったのでcloseします。
