### ISSUE TITLE
[不具合] Webフォームの「Webフォーム名」を編集できない

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#122]
**概要（Overview）**
作成したWebフォームを編集した際、「Webフォーム名」が編集できないです。

**再現手順（To Reproduce）**
1. システム設定> 自動化にある「Webフォーム」を選択
2. 既存のWebフォームを選択し、「編集」する
3. 「Webフォーム名」の名称を変更できない

**スクリーンショット（Screenshots）**
![#122_1](https://user-images.githubusercontent.com/77664240/113796601-8e15b380-978a-11eb-96da-d4c1a1939a9e.png)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: [Windows10]
- Browser [chrome]

**その他情報（Additional context）**

**Comment by Remicck** [comment]
@gatty2672 
Webフォーム名を使い、フォームの固有IDを生成している都合上、フォーム名は変更できない仕様となっていますので、どうしても名称を変更する場合は別フォームを作成していただけますか。

本画面は表示が紛らわしいため、Disableがわかりやすいように変更します。

**Comment by Remicck** [comment]
複製にて対応しましたのでこちらのIssueはクローズします。
