### ISSUE TITLE
[要望] ワークフローの実行時間を15分以下に設定したい

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#124]
**要望とその背景（Request and its background）**

スケジュールにある「ワークフロー」の周期を15分以下に設定できないため、
データ作成 ⇒ 作業担当者へのメール通知までタイムラグができてしまうため。

**Comment by Remicck** [comment]
@gatty2672 
config.inc.phpに以下のコードを入れることで、15分未満を指定することが可能になります。
```php
$MINIMUM_CRON_FREQUENCY = 5; // The minimum cron setup frequency is 5 minutes
```
翻訳ファイル上、「推奨周期は15分です」と表示されてしまいますので、`languages/ja_cp/Settings/CronTasks.php`も同様に修正する必要があります。

元々、多重実行を防止するための策として指定されている値ですので、利用には気をつけてください。

意味合いとして標準機能としての実装を望まれているのでしたら、現状開発は多重実行対策を入れる必要があるため、近々での対応は難しいです。

本件はこちらでCloseします。
