### ISSUE TITLE
[要望] リスト機能「すべて」の共有先を設定できるようにしてほしい

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#135]
**要望とその背景（Request and its background）**
モジュールのリスト機能を使用し、他ユーザが閲覧できるデータを制御しておりますが、
「すべて」のリストがデフォルトで表示されているため、全データを閲覧できてしまいます。

他リストと同じように、「ユーザの共有」を設定できるようにしてほしいです。

**Comment by Remicck** [comment]
ありがとうございます。
リストは特殊なリストで、他のリストの登録がないユーザーでも表示されるものとなります。
「すべて」で共有先を指定できるようにすると、どれのリストも表示できないユーザーが作成される可能性がありますので、こちらは対応しづらいです。

閲覧できるユーザーの設定は、プロファイルや役割、共有ルールの機能を用いて作成できるかと思いますので、もしよろしければ詳細な条件を教えていただけますか？

**Comment by Remicck** [comment]
本Issue自体はCloseしますが、こちらに記載いただければ回答致します。
