### ISSUE TITLE
[要望] 選択しているリストの色を変更してほしい

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#139]
**要望とその背景（Request and its background）**
F-RevoCRMの各モジュールにあるリスト機能にて、現在どのリスト内容が表示されているかわかりづらいため、
選択しているリストの色を薄いグレーからわかりやすい色に変更してほしいです。

![#133](https://user-images.githubusercontent.com/77664240/114341794-82186000-9b95-11eb-99fb-735af28194f3.png)

**Comment by Remicck** [comment]
ありがとうございます。
他のUIに合わせて調整します。
