### ISSUE TITLE
[不具合] 画面幅が狭いときドキュメントのアップロードが困難

### ISSUE THREAD

**Issue by Sota-Miyamoto** [thinkingreed-inc/F-RevoCRM#140]
**概要（Overview）**
右側があふれる
![image](https://user-images.githubusercontent.com/53038605/114353972-99147d80-9ba8-11eb-818b-0c6c1d7472aa.png)

**Comment by Remicck** [comment]
スマホ版でアップロードした時の症状でしょうか。
デバイスの横幅に応じてレイアウトするように調整します。

報告ありがとうございます。
