### ISSUE TITLE
[不具合] ブロック内のテキストエリアしかない場合の表示崩れ

### ISSUE THREAD

**Issue by amino1205** [thinkingreed-inc/F-RevoCRM#153]
**概要（Overview）**
 ブロック内のテキストエリアしかない場合の表示が崩れます

**再現手順（To Reproduce）**
1. ブロックを作成
1. ブロック内のフィールドにテキストエリアのみ複数設定にする
1. 詳細画面を開く
1. 表示が崩れている

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/65175138/115805216-7ba0a880-a41f-11eb-90d2-9439a93e1235.png)

実装イメージ
![image](https://user-images.githubusercontent.com/84700230/138417256-277d3d65-c7f5-43aa-8dd7-be35a54703e9.png)

**稼働環境 Server (please complate the following information):**
- OS: CentOS8
- PHP version PHP 7.4.11
- MySQL version MySQL 8.0.21

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser chrome
- Version 89.0.4389.128

**その他情報（Additional context）**

**Comment by Remicck** [comment]
@pavish69 
以前見たときはuitype20で確認してもらっていたと思いますが、uitype19のときに再現しそうなので、試してもらえますか？

**Comment by pavish69** [comment]
現状レポート
・項目1列のとき、テキストの左寄せを行いたい
・PR#126で、uitypeの変動が複雑になっている（？）

・ブロック内のテキスト幅構成は、以下のようになっている。
![image](https://user-images.githubusercontent.com/84700230/140900231-7bc93762-7880-4c88-accd-cc38d7e88ad2.png)
・ブロック内でuitypeを統一すると、正常な挙動を確認することができる
・uitype=19のとき、上図のような表示になる（項目1列、中央寄り）
・uitype=20のとき、実装イメージのような挙動が確認できる（項目1列、左寄り）
・項目を新規作成した際は、uitype=1にになり、項目は2列ずつ並ぶ
・画面下部の詳細情報は、uitype=21である

・layouts>v7>modules>Vtiger>DetailViewBlockView.tplにおいて、
104行目：
<td class="fieldValue {$WIDTHTYPE}" id="{$MODULE_NAME}_detailView_fieldValue_{$FIELD_MODEL->getName()}" {if $FIELD_MODEL->get('uitype') eq '19' or $fieldDataType eq 'reminder' or $fieldDataType eq 'recurrence'} colspan="3" {assign var=COUNTER value=$COUNTER+1} {/if}>
を
<td class="fieldValue {$WIDTHTYPE}" id="{$MODULE_NAME}_detailView_fieldValue_{$FIELD_MODEL->getName()}" {if 　$fieldDataType eq 'reminder' or $fieldDataType eq 'recurrence'} colspan="3" {assign var=COUNTER value=$COUNTER+1} {/if}>
に変更すると、実装イメージ通り表示されるが、下部の詳細情報項目が崩れる
・逆に、104行目を
<td class="fieldValue {$WIDTHTYPE}" id="{$MODULE_NAME}_detailView_fieldValue_{$FIELD_MODEL->getName()}" {if 　$fieldDataType neq 'reminder' or $fieldDataType neq 'recurrence'} colspan="3" {assign var=COUNTER value=$COUNTER+1} {/if}>
に変更すると、大部分は列数が反転するが、詳細部分は実装イメージ通りの表示になる。

**Comment by Remicck** [comment]
@pavish69 
いろいろ試しましたが、仕組み的に1行（最大2項目を表示）を表現するとき、テーブルレイアウトを使っている以上、colspan的な処理だけではやりたいことを実現するのは難しそうに感じました。

各ブロックでtableを生成している箇所の上部に、 `<tr><td></td>*4</tr>` を事前に入れておいて（高さ0の要素）強制的に4カラムだと認識させる感じが一番楽だとは思っています。
※Markup的には正しくないのですが・・・。
そっちで一旦PR作ってみます。
