### ISSUE TITLE
[不具合]エクスポートした見積PDFの値引き額（貴社特別値引き）に反映されない

### ISSUE THREAD

**Issue by miyax-tsunematsu** [thinkingreed-inc/F-RevoCRM#159]
**概要（Overview）**
ひとつの見積書全体に対する値引きを設定した時、エクスポートした見積PDFの値引き額（貴社特別値引き）に反映されない。

**再現手順（To Reproduce）**
不具合の発生手順を細かく記載してください。
（Steps to reproduce the behavior:）
1. 見積を作成し、項目を設定する。
1. 合計の下にある「(-) 値引き種別 (0)」をクリックし、値引き率または値引き額を設定する。
1. 値引き種別の右側のセルに値引き額が表示され、「税引き前の合計」も正しく計算されたことを確認し、見積を保存する。
1. その他→PDFにエクスポート（見積）をクリックし、PDFを出力する。
1. 見積PDFの「貴社特別値引き」の右側のセルには全体に対する値引き額は反映されない。（合計額は正しい）

**スクリーンショット（Screenshots）**
スクリーンショットがあれば添付してください。
（If applicable, add screenshots to help explain your problem.）
![image](https://user-images.githubusercontent.com/83848048/118229513-15132580-b4c7-11eb-9b40-8c02de3387da.png)
![image](https://user-images.githubusercontent.com/83848048/118229305-bea5e700-b4c6-11eb-9be6-2580ef22c83c.png)

**稼働環境 Server (please complate the following information):**
- OS: CentOS 7.9
- PHP version:
- MySQL version:

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser: chrome
- Version:  90.0.4430.212（Official Build） （64 ビット）

**その他情報（Additional context）**
- さくらのクラウド　マーケットプレイスのイメージを利用（イメージ利用日：2021年5月14日）

**Comment by Remicck** [comment]
@miyax-tsunematsu ご報告ありがとうございます。
現象のほう確認いたしますので、少々お待ち下さい。

**Comment by Remicck** [comment]
@miyax-tsunematsu 
「見積り」モジュールからPDFを出力する際に、PDFテンプレートを用いているのですが、その見積もり用PDFテンプレートに割引の項目が記載されていないことが原因のようです（内部的には計算できています）

サンプルのPDFテンプレートを作成しておりますので、少々お待ち下さい。

**Comment by Remicck** [comment]
@miyax-tsunematsu 
遅くなりました。
内部の計算は実施されていますが、PDFへ表示する部分で項目が足りていない不具合を現在修正しています。

別件の不具合として #169 があり、租税関係もあり一部切り上げ、切り捨てに不整合が見つかっています。
こちらも併せて対応予定となりますので、少々お待ち下さい。

**Comment by miyax-tsunematsu** [comment]
> @miyax-tsunematsu
> 遅くなりました。
> 内部の計算は実施されていますが、PDFへ表示する部分で項目が足りていない不具合を現在修正しています。
> 
> 別件の不具合として #169 があり、租税関係もあり一部切り上げ、切り捨てに不整合が見つかっています。
> こちらも併せて対応予定となりますので、少々お待ち下さい。

修正対応ありがとうございました。リリース楽しみにしております。
