### ISSUE TITLE
[不具合] システム設定画面でヘッダーが一部ずれる

### ISSUE THREAD

**Issue by Sota-Miyamoto** [thinkingreed-inc/F-RevoCRM#161]
**概要（Overview）**
システム設定画面のホームで画面幅を狭くするとヘッダーがずれて概要の文字が隠れている.

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/53038605/118434277-c01a1e00-b717-11eb-97eb-3745acc48d6e.png)

**Comment by pavish69** [comment]
設定＞ユーザー管理も同様である。
![image](https://user-images.githubusercontent.com/84700230/128310378-80e850f1-b4fa-40f4-8432-01f8d845ad93.png)
