### ISSUE TITLE
[不具合]画面幅が狭い際に左側のツールバーが消える

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#167]
**概要（Overview）**
画面幅が狭い際に左側のツールバーが消える。手順はFAQでの動作確認だが、それ以外のモジュールでも同じ不具合が発生する

**再現手順（To Reproduce）**
1. 通常ウィンドウでFAQの画面を開く
![image](https://user-images.githubusercontent.com/75693720/118467696-fa4ae600-b73e-11eb-9aa0-426b5b7b3749.png)
2. 画面サイズを狭める
![image](https://user-images.githubusercontent.com/75693720/118467735-0636a800-b73f-11eb-9182-c11325b97fcf.png)

**稼働環境 Server (please complate the following information):**

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser chrome

**その他情報（Additional context）**

**Comment by Remicck** [comment]
こちらはスマホ用のViewとして意図的に非表示にしています。
本件はCloseします。
