### ISSUE TITLE
[不具合] 関連>メールの項目が英語表記になっている

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#170]
**概要（Overview）**
顧客企業や案件等のレコードを開き、関連にある「メール」を選択すると、
「Access Count」「Click Count」の項目があるが、英語表記となっている

**再現手順（To Reproduce）**
1. 顧客企業モジュールを開く
2. 顧客企業に登録しているレコードを開く
3. メールアイコンをクリックする
4. 「Access Count」「Click Count」の項目が英語表記になっている

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/77664240/119423423-32a18400-bd3e-11eb-9db2-370900430f66.png)

**Comment by Sota-Miyamoto** [comment]
該当箇所は #86  で修正されています.
対象環境に適用されていないのかもしれません.
