### ISSUE TITLE
[不具合]「ユーザー名の変更」がパスワードがエラーで保存出来ない

### ISSUE THREAD

**Issue by ayako-hira** [thinkingreed-inc/F-RevoCRM#181]
**概要（Overview）**
ユーザ詳細画面「その他」の「ユーザー名の変更」から変更を行うと、パスワードがエラーで保存が出来ない

**再現手順（To Reproduce）**
1. システム設定＞ユーザ＞ユーザの詳細を開く
2. 右上のその他＞ユーザー名の変更
3. 新しいユーザー名とパスワードを入力
4. 条件通りにパスワードを入力しても「複雑なパスワードを指定ください」のエラーが出て保存出来ない

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/81276456/120428812-4ccb0a00-c3af-11eb-802f-d66fa776883a.png)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
OS: Windows10
Browser: Google Chrome

**その他情報（Additional context）**

**Comment by Remicck** [comment]
@ayako-hira ありがとうございます。確認して対応します。
