### ISSUE TITLE
[不具合]Calendar, view=Listにて、icsファイルをインポートした際の挙動について

### ISSUE THREAD

**Issue by masanori** [thinkingreed-inc/F-RevoCRM#191]
**概要（Overview）**
- 登録される時間が、ログインユーザが使っているTimeZone(UTC+9)でない。UTCであった。
- 登録後のresult画面が翻訳されていない

**再現手順（To Reproduce）**
- カレンダーのリストにて、インポート
- icsファイルを選択して、インポート実施

**スクリーンショット（Screenshots）**

![スクリーンショット 2021-06-08 111443](https://user-images.githubusercontent.com/295128/121112470-6b1b8480-c84b-11eb-903f-97a167bcf4cf.png)

**稼働環境 Server (please complate the following information):**
- 稼働環境依存ではないと思われるので、省略します。

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser: chrome

**その他情報（Additional context）**
- icsファイルの中身
```
BEGIN:VCALENDAR
PRODID:-//YouCanBook.me Ltd//YouCanBook.Me 1.18//EN
VERSION:2.0
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:YCBM-e01f292c-e426-40a1-a851-52967f373da1
DTSTAMP:20210608T020648Z
DTSTART:20210609T080000Z
DTEND:20210609T090000Z
SUMMARY:Your meeting with 
DESCRIPTION:
ORGANIZER:mailto:xxxx@example.com
ATTENDEE;RSVP=FALSE;ROLE=REQ-PARTICIPANT:mailto:xxxx@example.com
END:VEVENT
END:VCALENDAR
```

**Comment by Remicck** [comment]
@masanori 
ありがとうございます。

先程のコミット（ 217165761ce66975fa6e6d7eb4182d70e9fc2805 ）で修正しました。

**Comment by Remicck** [comment]
翻訳があったため、再度Openします。
