### ISSUE TITLE
[不具合]共有カレンダーにて参加者が2名以上いる予定をドラッグアンドドロップすると予定表示が2倍になる

### ISSUE THREAD

**Issue by masanori** [thinkingreed-inc/F-RevoCRM#198]
**概要（Overview）**
- 共有カレンダーにて参加者が2名以上いる予定をドラッグアンドドロップすると予定表示が2倍になる

**再現手順（To Reproduce）**
1. 予定登録を行う、その際、参加者に1名以上入れる
1. 上記予定を複数登録しておく（不具合の再現を分かりやすくするため）
1. 共有カレンダーを表示する
1. 共有カレンダーに参加者登録したユーザが表示されるようにしておく
1. 任意の参加者が1名以上いる予定をドラッグアンドドロップする
1. 再現する

**スクリーンショット（Screenshots）**
- なし

**稼働環境 Server (please complate the following information):**
- 関連性はないため省略

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10 pro
- Browser: バージョン: Chrome   91.0.4472.106（Official Build） （64 ビット）

**その他情報（Additional context）**
- ドラッグアンドドロップした際に、全予定を再取得しているためだと思われる

**Comment by Sota-Miyamoto** [comment]
自分の環境(ｍainブランチの最新コミット)では厳密には再現しませんでした.
ただ,共有カレンダーで複数の参加者がいる繰り返しの予定を動かすと10回に一回程度,表示が増殖することがありました.(さらに動かしたり,リロードするとすぐに戻る)

**Comment by hasesho28** [comment]
上記とは別手順ですが、恐らく同じ原因と思われる障害が発生したので再現手順を記載します。

前提：先週(ex.08/27)のいずれかに活動を作成しておく、共有カレンダーを週表示にしておく

1. 前提で作成した予定の「複製」ボタンから活動のクイック作成画面を開く
2. 今週(ex.08/31)に2.で開いたクイック作成から活動を作成する
3. 共有カレンダー右上の＞ボタンをクリックし、今週のカレンダーに移動する
4. 同様に＜ボタンをクリックし、先週のカレンダーに移動する
5. 更に＞ボタンをクリックし、今週のカレンダーに移動すると、同一の予定が2つずつ表示された状態となる

**Comment by Remicck** [comment]
私の場合（週次表示の場合）
1. 前週、または翌週＋今週に予定を 追加しておく
2. リロードする
3. 今週の予定を変更する
4. 保存完了後に前、または翌週へ遷移する

上記で再現しました。
