### ISSUE TITLE
[不具合]リストの複製をすると、項目と並び順の選択 に余計な項目が設定される

### ISSUE THREAD

**Issue by masanori** [thinkingreed-inc/F-RevoCRM#199]
**概要（Overview）**
- リストの複製をすると、項目と並び順の選択 に余計な項目が設定される

**再現手順（To Reproduce）**
1. 任意の数項目を設定したリストを作成する
1. 上記で作成したリストを複製する

**Comment by Remicck** [comment]
@masanori 
以下のような挙動となっていました。

- 複製時に、複製元となったリストの項目を表示する
- 「編集」ではない為 ＝ 新規作成と誤って、必須フィールドがリストの項目として表示される

軽微な修正となりますので、v7.3.4までに対応します。
