### ISSUE TITLE
[不具合]TODO管理において、ユーザ選択およびステータスが保持されない

### ISSUE THREAD

**Issue by masanori** [thinkingreed-inc/F-RevoCRM#205]
**概要（Overview）**
- TODO管理において、ユーザ選択およびステータスが保持されない。保持されて欲しい。
- 
**再現手順（To Reproduce）**
1. 画面ヘッダー部のチェックアイコンをクリック
2. TODO管理において、ユーザ選択およびステータスを任意のものを選択し、虫眼鏡アイコンをクリック
3. 結果が表示される
4. TODO管理を一度閉じて、上記手順１．の操作を行うとユーザ選択およびステータスが維持されず初期状態となる。

**スクリーンショット（Screenshots）**
- 添付しました。
![image](https://user-images.githubusercontent.com/295128/123045935-77503600-d436-11eb-9dfa-7df1a470abb5.png)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- chrome バージョン: 91.0.4472.106（Official Build） （64 ビット）

**Comment by Remicck** [comment]
一回機能改善として登録しましたが、調査したところ開くタイミングで常に上書きするような処理が有りましたので、バグに戻しました。
v7.3.4として対応します。
