### ISSUE TITLE
[不具合]ログイン時、ユーザー名が「ユーザ」で表示される

### ISSUE THREAD

**Issue by pavish69** [thinkingreed-inc/F-RevoCRM#212]
**概要（Overview）**
ログイン時、ユーザー名が「ユーザ」で表示される。

**再現手順（To Reproduce）**
１．ログイン画面
２．ユーザー名またはパスワードを間違う

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/84700230/123583881-57948580-d81b-11eb-9160-a41951979a06.png)

**稼働環境 Server (please complate the following information):**
- OS: [e.g. CentOS8]
- PHP version [e.g. PHP 7.4.11]
- MySQL version [e.g. MySQL 8.0.21]

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: [Windows10]
- Browser [chrome]

**その他情報（Additional context）**

**Comment by Remicck** [comment]
#213 こちらで対応しますので、クローズします。
