### ISSUE TITLE
[不具合]リマインダー機能の通知が表示されないケースが多い

### ISSUE THREAD

**Issue by masanori** [thinkingreed-inc/F-RevoCRM#215]
**概要（Overview）**
- リマインダー機能の通知が表示されないケースが多い
- 通知すべきActivityの条件に誤りがある

**再現手順**
- 活動またはTODOを作成する
- その際に、通知にチェックを入れる
- カレンダー設定＞アラームの表示間隔 を1時間にする
- →なかなかアラートが表示されない

**調査結果**
- 下記プログラムの該当箇所の条件の909, 910行と916, 917行目に着目
modules/Calendar/models/Module.php
```
 908                         $currentTime = time();
 909                         $date = date('Y-m-d', strtotime("+$activityReminder seconds", $currentTime));
 910                         $time = date('H:i',   strtotime("+$activityReminder seconds", $currentTime));
 911                         $reminderActivitiesResult = "SELECT reminderid, recordid FROM vtiger_activity_reminder_popup
 912                                                                 INNER JOIN vtiger_activity on vtiger_activity.activityid = vtiger_activity_reminder_popup.recordid
 913                                                                 INNER JOIN vtiger_crmentity ON vtiger_activity_reminder_popup.recordid = vtiger_crmentity.crmid
 914                                                                 WHERE vtiger_activity_reminder_popup.status = 0
 915                                                                 AND vtiger_crmentity.smownerid = ? AND vtiger_crmentity.deleted = 0
 916                                                                 AND ((DATE_FORMAT(vtiger_activity_reminder_popup.date_start,'%Y-%m-%d') <= ?)
 917                                                                 AND (TIME_FORMAT(vtiger_activity_reminder_popup.time_start,'%H:%i') <= ?))
 918                                                                 AND vtiger_activity.eventstatus <> 'Held' AND (vtiger_activity.status <> 'Completed' OR vtiger_activity.status IS NULL) LIMIT 20";
 919                         $result = $db->pquery($reminderActivitiesResult, array($currentUserModel->getId(), $date, $time));

```

- dateとtimeで別々に条件設定しているため、条件に合致するアラートが表示されない

**Comment by K-Haruto** [comment]
リマインダー機能に複数のバグがあったので箇条書きします。✓が入っている項目は修正が終わりテスト中です。

- [ ] アラーム通知間隔が長い場合(1時間、1日など)、いつまでも通知が表示されない。

1. アラームの通知間隔を1時間に設定する。1時間に設定されていた場合、1日に変更したのち1時間に設定する
2. 現在時刻から30分後、1時間後、2時間後の予定を作成する。
3. 待つ

結果、
![image](https://user-images.githubusercontent.com/75693720/126454720-b7fbd60e-b4ad-4a77-a5ed-d0881767997d.png)
30分後の予定は、通知が来ない(予定が終わった後に通知が入る)
1時間後の予定は、nextIntervalが経過した後に表示される
2時間後の予定は、nextIntervalが経過した後に表示される

- [ ] 通知が2個出てくる場合がある。
1. 翌日以降の予定を作成する
2. 作成した予定の時間を変更する。変更はカレンダー上のマウス移動で行う(下画像)
![image](https://user-images.githubusercontent.com/75693720/126455080-76489bb4-bc97-42a5-900a-8642e49287b2.png)

結果、
vtiger_activity_reminder_popupにCalendarとして複製されている

- [x]  dateとtimeで別々に条件設定しているため、条件に合致するアラートが表示されない

- [x]  予定を作成する際、通知するに✓を入れなくても通知が入る

**Comment by Remicck** [comment]
v7.3.7へ持ち越します。
