### ISSUE TITLE
[不具合]ウィジェットの追加のミニリスト作成の際、一部未翻訳

### ISSUE THREAD

**Issue by pavish69** [thinkingreed-inc/F-RevoCRM#218]
**概要（Overview）**
ウィジェットの追加のミニリストを作成する際、リスト一覧が英語のままになっている。

**再現手順（To Reproduce）**
1. トップ画面”ウィジェットの追加”
2. モジュールを選択
3. リストを選択
4. このリスト一覧が英語のまま

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/84700230/124445239-584c8f00-ddba-11eb-96c6-7fe258242ff0.png)
![image](https://user-images.githubusercontent.com/84700230/124445325-69959b80-ddba-11eb-9f49-ae1e12f029ba.png)

- 
**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: windows10
- Browser: chrome
- Version

**その他情報（Additional context）**

**Comment by Remicck** [comment]
#299 で対応済みな為Close
