### ISSUE TITLE
[質問]ワークフローで「項目の値の更新」後の画面の挙動について

### ISSUE THREAD

**Issue by kiyo-kun** [thinkingreed-inc/F-RevoCRM#223]
**質問内容（Contents of question）**
ワークフローで「項目の値の更新」を行った際に、画面の更新を行わないと変更された内容が表示されません。
これは何かしらの設定が必要なのでしょうか？
画面を更新するためのアクションを追加するとか？
それともそもそも画面の更新されるはずなのにされない？
または仕様なのでしょうか？

**Comment by Remicck** [comment]
@kiyo-kun 
レコードの更新は編集画面で行いましたか？
それとも、クイック編集（詳細画面の項目右側にある鉛筆マークを押して編集するアクション）を利用しましたか？

後者の場合、実際に編集を行った項目のみが変わりますので、ワークフローによって更新された項目は、画面上では変更されません。

**Comment by kiyo-kun** [comment]
コメントありがとうございます。
クイック編集を行いました。そういうものなんですね。
何かしら更新する方法はないものでしょうか？

**Comment by Remicck** [comment]
@kiyo-kun 
現状ではできませんので、要望としてIssueに入れていただけると助かります。
本Issueはクローズします。
