### ISSUE TITLE
[要望] 概要画面の活動に担当者を表示してほしい

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#228]
**要望とその背景（Request and its background）**
顧客企業の概要画面にて、顧客企業に関連する活動が表示されているが、
詳細情報を確認しないと誰の活動かわからないため、担当者が表示されるようにしてほしい。

■ イメージ図
![image](https://user-images.githubusercontent.com/77664240/125893838-9619cdf2-c102-4422-9df3-f6d8eb36a725.png)

**Comment by Remicck** [comment]
以下の情報を出してほしいという要望が多いため、改修予定です。
- 顧客担当者
- ステータス
- 活動タイプ
- 結果
