### ISSUE TITLE
[質問]F-RevoCRM version7.3.3で追加された関連項目として「ユーザー」を設定できる機能について

### ISSUE THREAD

**Issue by kiyo-kun** [thinkingreed-inc/F-RevoCRM#239]
**質問内容（Contents of question）**

関連項目として「ユーザー」を追加したのですが、
管理者ユーザー以外のユーザで設定をしようとした際に本人しか一覧に表示されません。

その他のユーザが表示されるような設定を探しましたがわかりませんでした。
ご教授お願い致します。

**Comment by Remicck** [comment]
@kiyo-kun 
ご質問ありがとうございます。
管理者以外の場合に、ロールベースでのユーザー一覧ではなく、自身のみが表示されるようになっておりました。
近日中に修正予定となりますので、少々お待ち下さい。
