### ISSUE TITLE
[不具合] JPG画像がアップロードできない

### ISSUE THREAD

**Issue by zeroadster** [thinkingreed-inc/F-RevoCRM#24]
**概要（Overview）**
顧客担当者、製品、ドキュメントなどでJPGファイルをアップロードできません。
PNG、BMP、GIF、PDFなどは問題なくアップロードできることを確認。
確認したモジュール
- 顧客担当者の画像
- 顧客担当者のコメントの添付
- ドキュメント
- 製品画像

**スクリーンショット**
SSは製品画像アップロード時のものです。
![image](https://user-images.githubusercontent.com/35953949/103736475-af53f000-5033-11eb-94d4-bd728b987849.png)

**稼働環境 Server (please complate the following information):**
- OS: Docker
- PHP version: 7.4
- MySQL version: 8.0

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Win10
- Browser: Chrome
- Version: 87

**Comment by Remicck** [comment]
ありがとうございます。
内容確認して、連絡しますのでお待ち下さい。

**Comment by zeroadster** [comment]
すみません、自己解決いたしました。

PHPのdockerfileの修正
30行目
- && docker-php-ext-install -j$(nproc) gd \
+ && docker-php-ext-install -j$(nproc) gd exif \

また、推奨設定でphp_short_code = Off ですが、そのままビルドするとOnになり、
画像ファイルに対してPHPコードインジェクションのチェックが行われ、「<?」が意外と頻繁に出るようです。
ですので、php.iniに
php_short_code = Off
を追加すれば、問題なさそうです。

デバッグログの出力を追加して、漸く判明しました。

**Comment by Remicck** [comment]
@zeroadster ありがとうございます。そのあたりだなとはあたりを付けていましたが、治ったようで安心しました。
もしよろしければその内容で問題なさそうなので、PR作っていただけますか？

**Comment by Remicck** [comment]
@zeroadster 
軽く調べたところ、正確にはshort_open_tagというオプションみたいです。
https://www.php.net/manual/ja/ini.core.php#ini.short-open-tag

こちらで試して問題なければ取り込めそうです。
調査ありがとうございました！

**Comment by zeroadster** [comment]
> short_open_tag
そうですね、失礼しました^^;
