### ISSUE TITLE
[不具合]案件の作成や更新を行った際の更新履歴のユーザが正しくない

### ISSUE THREAD

**Issue by kiyo-kun** [thinkingreed-inc/F-RevoCRM#257]
**概要（Overview）**
どのユーザーでログインして案件を作成や更新してもシステム管理者が行ったように履歴が残ります。

**再現手順（To Reproduce）**
1.案件を作成します。
2.作成した案件を更新します。
3.更新履歴を表示します。

**稼働環境 Server (please complate the following information):**
- F-RevoCRM version 7.3.3

**その他情報（Additional context）**
無し

**Comment by Remicck** [comment]
確認しますのでおまちください。

**Comment by Remicck** [comment]
@kiyo-kun 
手元の現在のmain環境では再現できませんでした。
環境はMacOS, Google Chrome, Dockerで、Testユーザーは「ゲストブラウザ」を使っています。
![スクリーンショット 2021-08-19 10 26 19](https://user-images.githubusercontent.com/3492320/129993067-b853b947-852b-43df-8119-a281c7b6bb73.png)

ログインは別タブではなく、ゲストブラウザなどで変えていますか？

**Comment by kiyo-kun** [comment]
環境はWin10,Google Chrome,さくらのクラウドです。

こちらの環境ではこのように出ます。
![不具合イメージ](https://user-images.githubusercontent.com/11715730/129997681-fc250c2a-d50d-4389-9fb8-7350454e92b9.png)
ゲストブラウザでログインして試しました。
黒塗りのユーザでBR1を1に更新したのですが更新者がシステム管理者になりました。

影響ないだろうと伝え忘れていたことがありました。
https://github.com/thinkingreed-inc/F-RevoCRM/pull/243/commits/fc984e315cc6d88b1ff5b7d88e8bbdf14fd75573
こちらの対応を試しで入れていました。
このソースの影響であればクローズしてもらって良いです。
申し訳ありません。

**Comment by kiyo-kun** [comment]
https://github.com/thinkingreed-inc/F-RevoCRM/issues/261
こちらの不具合のようです。
こちらはクローズします。

**Comment by Remicck** [comment]
@kiyo-kun 
ありがとうございます。#261の方で対応しますのでお待ち下さい。
