### ISSUE TITLE
[要望]vTigerCRM 7.4の取り込み

### ISSUE THREAD

**Issue by Remicck** [thinkingreed-inc/F-RevoCRM#258]
**要望とその背景（Request and its background）**
https://code.vtiger.com/vtiger/vtigercrm/commits/7.4.0
7.4が公開されているので、修正点をマージする

**その他情報（Additional context）**

**Comment by Remicck** [comment]
Milestonは7.3.5とするか、7.4.0とするか検討中です。

**Comment by junmt** [comment]
7.4.0の際にほぼ取り込んでいるはずなので、クローズする。
