### ISSUE TITLE
[不具合]パスワードを日本語翻訳漏れ

### ISSUE THREAD

**Issue by pavish69** [thinkingreed-inc/F-RevoCRM#259]
**概要（Overview）**
不具合の内容を簡潔に記載してください。
（A clear and concise description of what the bug is.）
パスワードを変更した際の日本語翻訳漏れ

**再現手順（To Reproduce）**
不具合の発生手順を細かく記載してください。
（Steps to reproduce the behavior:）
1. システム設定＞ユーザ＞ユーザの詳細を開く
2. 右上のその他＞パスワードの変更
3. 新しいパスワードを入力（アルファベット大文字・小文字、数字、記号を含む8文字以上）
4. 保存する

**スクリーンショット（Screenshots）**
スクリーンショットがあれば添付してください。
（If applicable, add screenshots to help explain your problem.）
![image](https://user-images.githubusercontent.com/84700230/130000670-77b41f29-dc01-4699-8812-939f17fb0393.png)

**稼働環境 Server (please complate the following information):**
- OS: [e.g. CentOS8]
- PHP version [e.g. PHP 7.4.11]
- MySQL version [e.g. MySQL 8.0.21]

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: [Windows10]
- Browser [chrome]
- Version [22]

**その他情報（Additional context）**

**Comment by Remicck** [comment]
0664aa63ee1784b48b3a485555b0b4a881e2b4d4
対応済みのため、Closeします。
