### ISSUE TITLE
[不具合]タグのインポートができない

### ISSUE THREAD

**Issue by ratorin** [thinkingreed-inc/F-RevoCRM#285]
**概要（Overview）**
不具合の内容を簡潔に記載してください。
（A clear and concise description of what the bug is.）
インポート時、タグを選択できるが、値が反映されない。

**稼働環境 Server (please complate the following information):**
Xserver
- OS: Linux 不明
- PHP version PHP 7.4.13
- MySQL version MariaDB10.5

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser chrome
- Version 93.0.4577.63

**その他情報（Additional context）**

**Comment by Sota-Miyamoto** [comment]
タグはvtiger_freetags及びvtiger_freetagged_objectsテーブルで独自に管理されていますが,/modules/Import内を検索してもtagに関する特別の処理は見つからなかったことから,そもそもタグのインポートは考慮されていない可能性が高いです.

**Comment by Remicck** [comment]
こちらは機能改善として、仕様を決めてインポート、エクスポート可能な形にすることが望ましいと考えています。
現状では
- カンマ区切りのタグ出力（エスケープ処理含む）
- カンマ区切りで取り込み
上記仕様に従って実装する方針です。

**Comment by ratorin** [comment]
実装ありがとうございます。パッチ楽しみにしてます。

**Comment by Remicck** [comment]
@Sota-Miyamoto 
カンマ区切りだとCSVフォーマットで少し処理がややこしいので、複数選択ピックリストと同じように、|##|で区切る実装にそろえてもらえますか？
