### ISSUE TITLE
[不具合] webフォームからhtmlファイルを添付送信するとファイルの拡張子がおかしくなる

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#286]
**概要（Overview）**
webフォームからhtmlファイルを添付送信するとファイルの拡張子がおかしくなる
**再現手順（To Reproduce）**
1. 自動化＞webフォームにて、"ドキュメントのアップロード"の項目を追加したフォームを作成する
2. 作成したフォームにアクセスし、htmlファイルを添付して送信する(例ではform.htmlを添付)
3. 送信先にアクセスし、フォーム内容を確認する(form.htmlfile.txtという名前で表示される)

**スクリーンショット（Screenshots）**
![キャプチャ](https://user-images.githubusercontent.com/75693720/133051148-a4d55289-912c-4f34-9303-7bcf649a25a6.PNG)

**稼働環境 Server (please complate the following information):**

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser chrome
- Version

**その他情報（Additional context）**

**Comment by Remicck** [comment]
@K-Haruto 
特定のファイルの場合、DL後に意図せず実行してしまう可能性があるため、拡張子をシステム側で変更しています。
以下の拡張子の場合、自動で「ファイル名」＋file.txtというファイル名としてF-RevoCRMに保存されます。

本Issueはクローズします。
