### ISSUE TITLE
[要望]ユーザーの管理項目をシステム設定の画面上から変更できるようにしてほしい

### ISSUE THREAD

**Issue by mozukuudon** [thinkingreed-inc/F-RevoCRM#289]
**要望とその背景（Request and its background）**
管理項目・必須項目を増やしたいため
**その他情報（Additional context）**

**Comment by Remicck** [comment]
先日の修正でUsersモジュールは項目を変更できないように修正しております。
要望として多いため、この部分も標準機能で対応できるように回収できればと考えていますので、少々お待ち下さい。

**Comment by Remicck** [comment]
本Issueは次回パッチ対応とします。
制限事項として、vtiger_usersテーブルにのみ追加可能な形で実装しますので、最大行サイズである65,535バイトに依存します。
[MySQL :: MySQL 5\.6 リファレンスマニュアル :: D\.10\.4 テーブルカラム数と行サイズの制限](https://dev.mysql.com/doc/refman/5.6/ja/column-count-limit.html)

**Comment by Remicck** [comment]
@kkouta からPRお願いします。
@K-Haruto はサブでお願いします。
