### ISSUE TITLE
[要望]ワークフロー保存後に、すべてのワークフローに遷移してしまう

### ISSUE THREAD

**Issue by Remicck** [thinkingreed-inc/F-RevoCRM#313]
**要望とその背景（Request and its background）**
複数のワークフローを設定している場合、毎回すべてのワークフローに遷移することが不便。
以前開いていたワークフローの検索条件の一覧を表示してほしい。

**その他情報（Additional context）**

**Comment by Sota-Miyamoto** [comment]
Issue #370 と同一です. Pull request #416  で修正しました.
