### ISSUE TITLE
[要望] 項目のラベル名を変更できるようにしてほしい

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#316]
**要望とその背景（Request and its background）**

デフォルトからある項目や新規作成した項目のラベル名を変更できるようにしてほしいです。
⇒ 画面上から項目のラベル名を変更するには、システム設定にある文言変更を使用するか、
項目を作り直さないといけないので運用しづらい。

**その他情報（Additional context）**

**Comment by kkouta** [comment]
#557 にて対応させていただきます。

**Comment by Remicck** [comment]
#557 で対応するためClose
