### ISSUE TITLE
[要望] 生年月日を入力することにより、現在の年齢を表示されるようにしてほしい

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#319]
**要望とその背景（Request and its background）**
顧客やスタッフ情報を入力する際に年齢を入力することがあるので、
生年月日を入力することで年齢計算を行い、現在の年齢を表示されるようにしてほしい
⇒ 年齢データの手動更新は運用上難しいため

**その他情報（Additional context）**

**Comment by kkouta** [comment]
ワークフローの項目を更新するアクションに年齢を表示する機能を作成いたしました。今後のアップデートにて追加予定です。

以下に基本情報に年齢を表示させる方法を記載いたします。
・顧客担当者の一覧画面の右上にあるカスタマイズから項目の編集を選択する。
・新しい項目を追加を選択していただき、項目タイプの選択ー＞整数、長さー＞３を選択し保存する。ラベル名は自由に入力してください。
・システム設定ー＞自動化ー＞ワークフローの右上の「新しいワークフロー」を選択し、基本情報、タイミング、条件を入力。
・アクションの追加の「項目の値の更新」を選択し先ほど追加した項目を追加する。
・右の空欄をクリックし、表現式を選択し「関数の利用」から「age」を選択し保存する。

**Comment by Remicck** [comment]
scheduled workflowでも動くことを確認しています。

**Comment by maruyo** [comment]
念願の年齢表示が実装されたと聞いて試してみました。
関数ageを選択したときに自動で入力されるのがget_age(date)のため正しい年齢が表示されず手動でget_age(birthday)に変更する必要があるようです。
