### ISSUE TITLE
[要望]項目設定画面にて、関連項目でのユーザーモジュール指定できるようにしてほしい

### ISSUE THREAD

**Issue by NakaYuka2451** [thinkingreed-inc/F-RevoCRM#32]
**要望とその背景（Request and its background）**
案件モジュールなどで案件担当以外に複数の担当を設定したいため
（例えば、一つの案件に対して営業の担当、サポートの担当、開発の担当　など割り当てて利用したい。）

**その他情報（Additional context）**
![image](https://user-images.githubusercontent.com/70676476/107198270-3d0e6b00-6a38-11eb-90b3-a0257b66e8d4.png)

**Comment by Remicck** [comment]
ユーザーモジュールを関連に追加することは可能ですし、出すだけであればすぐ実装できそうですが、権限上の影響が出る可能性がありますので、設計、検証の上で実装したいと思います。
※表示してはいけないユーザーなどが表示される可能性を考慮
