### ISSUE TITLE
[不具合]一覧リストの｢その他｣ボタンを押したあと上部メニューを押すと重なってしまう

### ISSUE THREAD

**Issue by Sota-Miyamoto** [thinkingreed-inc/F-RevoCRM#33]
**概要（Overview）**
一覧リストの｢その他｣ボタンを押したあと上部メニューを押すと重なってしまう

**再現手順（To Reproduce）**
不具合の発生手順を細かく記載してください。

1. 一覧リストを開く
1. ｢その他｣ボタンを押す
1. 上部のメニューを押す

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/53038605/107450428-908fce80-6b88-11eb-9cf5-9a728d1bbf49.png)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS:Windows10
- Browser:chrome

**その他情報（Additional context）**

**Comment by Remicck** [comment]
別のエリアを押すと消えるので、優先度は低めにさせてください。
もし対応できそうでしたらPRを送ってもらえれば取り込みます。

報告ありがとうございます。
