### ISSUE TITLE
[不具合]項目追加時に項目タイプを何回か切り替えると、デフォルト値の表示がおかしくなる

### ISSUE THREAD

**Issue by ayako-hira** [thinkingreed-inc/F-RevoCRM#350]
**概要（Overview）**
 カスタム項目の追加から項目タイプを何回か切り替えると、デフォルト値の枠が消えたり勝手にnullになったり表示がおかしくなることがある。

**再現手順（To Reproduce）**
1. 項目設定＞カスタム項目の追加
2. 項目タイプを「選択肢(複数)」または「関連」にしてから、別の項目タイプを選択
3. デフォルト値の枠が消えたり勝手にnullになったりする

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/81276456/139770368-22bc9399-4c96-4d32-a185-2b8a24296ad5.png)
![image](https://user-images.githubusercontent.com/81276456/139770350-c5bfdc1a-f0a2-4bd7-97ba-4ab8ad67dc6e.png)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
-  Windows10
- chrome

**Comment by Remicck** [comment]
@K-Haruto 
デフォルトの項目が出ているところは確認しました。
そのまま設定をして保存しましたが、デフォルト値の設定が保存できませんでした。

フィールドにデフォルト値が保存できているか。
また、新規作成画面を開いたときに、初期値でその値が入るかを確認してください。

よろしくお願い致します。

**Comment by K-Haruto** [comment]
顧客企業に項目を追加してテストしてみました。デフォルト値の保存ができない不具合は再現されませんでした。
ただ、項目の**編集時**に複数選択肢のデフォルト値が削除されるバグは発見しました。今回の項目切り替えとは別issueとして報告します。

**テスト内容**
 - 顧客企業に複数選択肢のカスタム項目を作成。デフォルト値をa, bbの2つ設定
項目画面
![image](https://user-images.githubusercontent.com/75693720/153976618-89268486-70a6-46ea-8988-11b77dee578a.png)
DB詳細
![image](https://user-images.githubusercontent.com/75693720/153976537-82334589-8c1a-4459-b002-80660ed25696.png)
顧客企業新規作成画面
![image](https://user-images.githubusercontent.com/75693720/153976831-e1064427-8f4b-40b7-80b7-090c0f4f3731.png)

 - 顧客担当者にテキスト(単数行)の項目を作成 → 正常にデフォルト値が保存される。新規画面でも表示される
 - 案件にチェックボックスの項目を作成 → 同上
