### ISSUE TITLE
[不具合]活動のリストにToDoのステータスを表示していないと活動の完了アイコンが次の予定登録アイコンに切り替わらない

### ISSUE THREAD

**Issue by junmt** [thinkingreed-inc/F-RevoCRM#362]
**概要（Overview）**
活動やToDoが完了ステータスになった際に、一覧画面で旗印（次の予定登録アイコン）が表示される。
しかし、ToDoのステータスを表示していないとチェックマーク（ステータスを完了にするアイコン）が表示されたままになり、次の予定を一覧から直接登録することができない。

**再現手順（To Reproduce）**
1. 活動の一覧を開く
2. リストを作成する（活動のステータスをリスト内に含めない）
3. 作成したリストに完了ステータスの活動とToDoを表示させる
4. 完了ステータスの活動やToDoがチェックマークのアイコンのままになる

**スクリーンショット（Screenshots）**
なし

**稼働環境 Server (please complate the following information):**
環境は関係なし

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
ブラウザ関係なし

**その他情報（Additional context）**
include/ListView/ListViewController.php
getListViewRecords関数内の以下の「+」の部分を追記すれば意図した通りに動作する。

if($module == 'Calendar' && ($fieldName == 'taskstatus' \|\| $fieldName == 'eventstatus' \|\| $fieldName == 'activitytype')) {
$value = Vtiger_Language_Handler::getTranslatedString($value,$module);
$value = textlength_check($value);
+ if(!in_array('taskstatus', $listViewFields) && $fieldName == 'eventstatus') {
+ $row['taskstatus'] = $value;
+ }
} else {
$value =  Vtiger_Language_Handler::getTranslatedString($value,$module);
$value = textlength_check($value);

**Comment by Sota-Miyamoto** [comment]
再現を確認したので調査結果をまとめます。
修正は未完成です。
- リストビューの｢ステータス｣には内部的に｢ステータス(活動)｣と｢ステータス(TODO)｣が存在する
- ｢ステータス(活動)｣は活動のステータスのみを表示する
- ｢ステータス(TODO)｣は活動とTODO両方のステータスを表示する
- リストビューの旗印アイコンは｢ステータス(TODO)｣を表示している場合のみ表示される
- テンプレートファイルで旗印アイコンを制御する際に｢ステータス(TODO)｣が｢完了｣の場合のみ表示するようにしている
- 画面生成側でリストに｢ステータス｣が存在する前提で制御しているため、｢ステータス｣を表示していない場合は全く表示ができない
- record_modelを取ってきて制御する(予定)
