### ISSUE TITLE
[不具合]ユーザー一覧の罫線が消えることがある

### ISSUE THREAD

**Issue by junmt** [thinkingreed-inc/F-RevoCRM#363]
**概要（Overview）**
システム設定＞ユーザー一覧の罫線が消えることがある。

**再現手順（To Reproduce）**
1. ユーザー一覧を開く
2. 最初の3列ぐらいの罫線が消えている

※再現パターンが分からず。少人数の場合は発生？

**スクリーンショット（Screenshots）**
なし

**稼働環境 Server (please complate the following information):**
環境依存なし

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
ブラウザ依存なし

**その他情報（Additional context）**
HTMLのタグの構成が他のリストと異なるために発生していた。
下記の修正で直ります。
![image](https://user-images.githubusercontent.com/12598156/141929515-d65c5317-864a-4771-bef9-32333c12ff53.png)

**Comment by pavish69** [comment]
再現方法
・画面の幅を小さくしたとき
![image](https://user-images.githubusercontent.com/84700230/144948380-f9044f59-bb8c-4232-bf2e-cfdd77bcfe81.png)
