### ISSUE TITLE
[要望]関連項目を追加した際にINDEXを付与して欲しい

### ISSUE THREAD

**Issue by junmt** [thinkingreed-inc/F-RevoCRM#364]
**要望とその背景（Request and its background）**
レポート等で結合条件として使われるので、INDEXがないと遅くなる。

**その他情報（Additional context）**

![image](https://user-images.githubusercontent.com/12598156/141930016-5dd57859-cd8d-4fe2-8afd-8090244714a1.png)

**Comment by Remicck** [comment]
できれば既存の関連項目もマイグレーション時にIndexを付与するようにしたいです。

**Comment by Remicck** [comment]
>できれば既存の関連項目もマイグレーション時にIndexを付与するようにしたいです。
こちらは別Issueで立てます。
