### ISSUE TITLE
[質問]PDFテンプレートのフォント変更について

### ISSUE THREAD

**Issue by ratorin** [thinkingreed-inc/F-RevoCRM#366]
**質問内容（Contents of question）**
PDFテンプレートの日本語フォントですが、0に点が入ってしまいます。
金額などは英字フォントにすればいいのですが、住所の番地などは変更できず・・・
他の日本語フォントに切り替えるやり方がありましたら教えてください。
よろしくお願いします。

**Comment by Remicck** [comment]
@ratorin 
フォントについては検討されていて、また現在内部で利用しているTCPDFのCSSで維持れる範囲に限界があるので、HeadlessChromeを使う実装にするか悩んでいるところです。

フォントについては基本的にTCPDFの仕様に準拠しているので、指定の方法でファイルを置くことで変更可能です。
`libraries/tcpdf/fonts`

また、設定は複数の場所に点在しているのですが、
`$pdf->SetFont` 関連のメソッドで指定している箇所を追加したフォント名に書き換えることでフォントの変更は可能です。

HeadlessChromeに関しては続報をこちらに書くようにします。

**Comment by ratorin** [comment]
お返事ありがとうございます。
こちらを参考に
https://demo.tkita.net/moodledocs/35/ja/ceed8fdd0bedda729614be30225dad63.html
出力されたファイルを、直接　ume-tgo4　に変更して上書いたところうまくいきました。

ありがとうございました。
