### ISSUE TITLE
[要望]タグの所有者をわかるようにしてほしい

### ISSUE THREAD

**Issue by masanori** [thinkingreed-inc/F-RevoCRM#369]
**要望とその背景（Request and its background）**

テスト的に作成したタグを削除したいときなど、所有者がわからないと削除ができない。
タグの編集時に所有者が分かれば、現在の削除機能で確実に削除でき、修正の手間も少ないと思われる。

**Comment by Remicck** [comment]
@yutakoseki 
タグのポップアップで出てくる編集画面に、所有者の名前を出してください。
