### ISSUE TITLE
[不具合]画面半分のウィンドウで「システム管理」を閲覧すると文字が重なって見える

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#37]
**概要（Overview）**
画面半分のウィンドウで「システム管理」を閲覧すると文字が重なって見える

**再現手順（To Reproduce）**
1. システム管理の画面を開く
2. ウィンドウを左半分(右半分)にする

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/75693720/107462723-19663480-6ba0-11eb-8926-972da92e5824.png)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: windows10
- Browser: chrome

**その他情報（Additional context）**
- ディスプレイの解像度: 1920×1080

**Comment by Remicck** [comment]
@K-Haruto 
ありがとうございます。
具体的には830px - 1100px付近で、トップページのメニュー表示状況にもよりますがカラム落ちのような症状が起きているのを確認しました。

この部分はどのように表示すべきかも含めて検討して対応します。
