### ISSUE TITLE
[不具合]ワークフロー新規作成・保存後の画面遷移で、フィルタが解除されて「全て　ワークフロー」になってしまう

### ISSUE THREAD

**Issue by masanori** [thinkingreed-inc/F-RevoCRM#370]
**概要（Overview）**

ワークフロー新規作成・保存後の画面遷移で、フィルタが解除されて「全て　ワークフロー」になってしまう

**再現手順（To Reproduce）**
1. ワークフローで左上のドロップダウンから、任意のモジュールを選択する
2.  ワークフローを"新しいワークフロー"ボタンをクリックし、新規作成し保存する
3.  「全て　ワークフロー」の一覧に戻ってしまう。→手順1.のモジュールで絞り込まれている一覧に遷移してほしい。

**Comment by Sota-Miyamoto** [comment]
概ね修正が終わったのでテスト後プルリクエストにします.
フィルターなし状態で保存した際にフィルターあり状態にするか,フィルターなし状態するかは微妙ですが,現状フィルターありになります.
