### ISSUE TITLE
[質問]並び順の基準は何？

### ISSUE THREAD

**Issue by ratorin** [thinkingreed-inc/F-RevoCRM#376]
**質問内容（Contents of question）**
お世話になっております。
見積時に出てくる製品一覧からこの疑問が始まったのですが、
標準の並び順は何を基準にされているのでしょうか。
登録順でも製品名順でもなくよくわかりませんでした。

型番に数字を入れて並び替えをして対応をしておりますが、できれば標準の並び順をコントロールしたいです。

わかれば教えてください。

**Comment by Remicck** [comment]
@ratorin 
見積もりで製品を取得する際は以下の二種類があり
![スクリーンショット 2021-11-19 15 05 59](https://user-images.githubusercontent.com/3492320/142573594-49c36e51-18a3-4361-b4ba-2afb9c5e18e0.png)
こちらは「最終更新日の降順」となります。
その他リスト画面等、最終更新日の降順による表示が殆どの部分で利用されています。

並び順については`Vtiger_ListView_Model::getListViewEntries`で取得されますので、特定のモジュールの場合（今回の場合は製品＝Products）、継承先の`Products_ListView_Model`のSQL上でOrderByを修正する事によって、並び順を変更できます。

![スクリーンショット 2021-11-19 15 05 46](https://user-images.githubusercontent.com/3492320/142573662-53ac2ff0-93ac-4e72-8da1-53b100aaa8e0.png)
インライン検索の場合、検索条件を入れておりませんので、`vtiger_crmentity` が出力する並び順に準拠します。
おそらくですが、`vtiger_crmentity.crmid` がプライマリーキーとなっていますので、この昇順となっているかと思われます（つまり作成順）
※APIのエンドポイントは以下のファイル、またはその継承先です。
`modules/Vtiger/models/Module.php:1464`
```php
public function getSearchRecordsQuery($searchValue,$searchFields, $parentId=false, $parentModule=false) {
			$db = PearDatabase::getInstance();
			$query = $db->convert2Sql("SELECT ".implode(',',$searchFields)." FROM vtiger_crmentity WHERE label LIKE ? AND vtiger_crmentity.deleted = 0", array("%$searchValue%"));
	return $query;
}
```

これらについてはご要望をいただくケースが多いため、設定レベルでデフォルトの並び順が定義できないか、検討させていただければと思います。

お手数ですが機能改善のIssueを立ててもらえますか？

**Comment by Remicck** [comment]
#375 を本Issueの機能改善として対応します。
