### ISSUE TITLE
[不具合]関連メニューの「活動」から、詳細ページに遷移したとき、左サイドバーがマーケティングのものになってしまう

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#38]
**概要（Overview）**
関連メニューの「活動」から、詳細ページに遷移したとき、左サイドバーがマーケティングのものになってしまう
本来であれば、活動表示時の個人カレンダーや共有カレンダーのリンクが出るべき。

**再現手順（To Reproduce）**
不具合の発生手順を細かく記載してください。
（Steps to reproduce the behavior:）
1. マーケティングから顧客企業のページを表示する
2. 顧客企業を選択
3. 関連メニューの活動から予定を選択
4. 詳細を表示する

**Comment by Remicck** [comment]
@K-Haruto 
手元の環境で再現できませんでした。
発生した状況の詳細、スクリーンショット付きでもらえますか？
