### ISSUE TITLE
[不具合]PriceBooksモジュールに画面から追加した項目を、関連としてレポートで使用するとエラーになる

### ISSUE THREAD

**Issue by hasesho28** [thinkingreed-inc/F-RevoCRM#381]
**概要（Overview）**
PriceBooksモジュールに項目設定から追加した項目を、レポートで使用するとエラーが発生する。

**再現手順（To Reproduce）**
不具合の発生手順を細かく記載してください。
（Steps to reproduce the behavior:）
1. 項目設定から、価格表（PriceBooks）モジュールを選択する
2. 適当なフィールドを新規で追加する。その際、項目タイプを整数など、レポートで集計対象となるようにする。
3. レポートを作成する。関連として価格表（PriceBooks）モジュールを使用する(e.g. 主モジュール：製品、関連：価格表)
　また、手順2で追加したフィールドの任意の計算項目を選択し、レポートを作成する。
4. エラーが発生

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/84055994/143436518-5a599ebe-a201-4d73-bb26-f12b43c23ce7.png)

不具合発生時の利用ブラウザ Blowser(please complete the following information):
OS: Windows10
Browser chrome
Version latest

**Comment by Remicck** [comment]
取り急ぎ価格表モジュールについては、暫定対応を行い、根本的な原因は#357 にて管理し対応します。
#357 はv7.3.6にて対応予定です。
