### ISSUE TITLE
[不具合]Contactsのportalをonとした際に送られてくるメールがすべて英語。

### ISSUE THREAD

**Issue by masanori** [thinkingreed-inc/F-RevoCRM#385]
**概要（Overview）**
Contactsのportalをonとした際に送られてくるメールがすべて英語。

**再現手順（To Reproduce）**
不具合の発生手順を細かく記載してください。

1. システム設定＞自動化＞ワークフロー において、「Send Email to user when Portal User is True」を有効にする。アクションも有効にする。
2. 顧客担当者のportalにチェックを入れて保存
3. 顧客担当者のemailに入っているメールアドレスへ送信されるメール内容が英語

- 対象のアクションは下記
modules/Contacts/ContactsHandler.php
`
 11 function Contacts_sendCustomerPortalLoginDetails($entityData){
`

- メールの内容は下記
modules/Contacts/Contacts.php
`
1574         public static function getPortalEmailContents($entityData, $password, $type='') {
`

**Comment by kkouta** [comment]
Contactsのportalをonとした際に送られてくるメールの文章はご利用者様自身で編集することも可能です。
方法を下記に記載いたします。

1.ツール＞メールテンプレートを開くとメールテンプレートの一覧が表示されます。
2.一覧の内のCustomer Login Detailsを開きます。
3.右上にある「編集」を選択し、メール文を編集します。
4.編集後、保存を選択します。

手順の3において他のメールテンプレートを選択することで本件以外のメール文も編集することができます。

また今回の問題を受け新しくソフトをインストールした際には自動でメールの文章が日本語に修正されるようする予定です。
本Issueは初期インストール時に、日本語で追加されるようになった際にCloseします。

**Comment by kkouta** [comment]
新しくソフトをインストールした際に自動でメールの文章が日本語に修正されるようにいたしました。
