### ISSUE TITLE
[要望]カレンダーのマイグループのユーザーチェック欄を一括選択・一括解除できるようにしてほしい

### ISSUE THREAD

**Issue by masanori** [thinkingreed-inc/F-RevoCRM#386]
**要望とその背景（Request and its background）**
- マイグループの人数が多いと一括選択・解除ができるだけで利便性が向上します。

**Comment by Remicck** [comment]
@masanori #258 vTigerCRM 7.4で対応されているので、こちらで取り込みますのでこちらはCloseします。
v7.3.6を目標にしていますが、難しい場合はv7.3.7になります。
