### ISSUE TITLE
[不具合]カレンダー上から詳細入力を行ったあとの戻り先が遷移元のカレンダーにならない

### ISSUE THREAD

**Issue by masanori** [thinkingreed-inc/F-RevoCRM#387]
**概要（Overview）**
カレンダー上から詳細入力を行ったあとの戻り先が遷移元のカレンダーにならない
不具合といっていいぐらい、不便

**Comment by Remicck** [comment]
`layouts/v7/modules/Calendar/resources/Calendar.js:1707`付近で
```javascript
defaultDate: new Date('2021-03-01'),
```
のようにすると該当の日付で開くようになるので、Cookieやパラメーターを渡す方法などで戻り日を指定できるようにする。
