### ISSUE TITLE
一覧画面で一部の区切り線が消える

### ISSUE THREAD

**Issue by mozukuudon** [thinkingreed-inc/F-RevoCRM#389]
**概要（Overview）**
各モジュールの一覧画面を開いたとき、先頭項目の区切り線が一部消えているものがある。

**再現手順（To Reproduce）**
一覧画面を開いたとき不定期に発生。

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/81809093/143985813-32b8ce88-4a6e-47e3-b774-9fc0b56e79a2.png)

**稼働環境 Server (please complate the following information):**
社内、デモ環境ともに発生

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
chrome,最新

**その他情報（Additional context）**

**Comment by Remicck** [comment]
こちらは`position: sticky;`で左列を固定した際に、`transform: scale(0.999);`を指定することによって発生しています。
現在調べると、scaleを入れる必要がないようにも見えますので、修正後再現するかを確認しつつ、対応します。

ありがとうございます。

**Comment by Remicck** [comment]
`trasform: scale(0.999) → trasform: scale(0.9)` などにすると問題は解決されるが、エリアが著しく小さくなってしまい現実的ではない。

以下の方針で対応してください。
`position: sticky` がついている要素に、
- `border-bottom` を追加する。
- `transform: scale(0.999)` を削除する
- last-childには`border-bottom` は適用しないようにする（罫線が二重に表示されておかしくなる。）
