### ISSUE TITLE
[不具合]カスタム項目「選択肢(単数)」のデフォルト値表示がおかしい

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#393]
**概要（Overview）**
カスタム項目「選択肢(単数)」のデフォルト値表示がおかしい
#350 の修正中に発見

**再現手順（To Reproduce）**
1. カスタム項目作成画面「選択肢(単数)」を表示する
2. デフォルト値をクリック
3. 「オプションの選択」が2個表示される

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/75693720/144358746-97b65b9e-6537-423c-89b3-af3c15ca7857.png)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser: chrome

**その他情報（Additional context）**

**Comment by Sota-Miyamoto** [comment]
発生を確認しました。
layouts\v7\modules\Settings\LayoutEditor\DefaultValueUi.tplの
```
{if $FIELD_MODEL->getFieldDataType() eq "picklist"}
	{if !is_array($PICKLIST_VALUES)}
		{assign var=PICKLIST_VALUES value=$FIELD_INFO.picklistvalues}
	{/if}
	{if !$DEFAULT_VALUE}
		{assign var=DEFAULT_VALUE value=$FIELD_MODEL->get('defaultvalue')}
	{/if}
	{assign var=DEFAULT_VALUE value={decode_html($DEFAULT_VALUE)}}
	<select class="col-sm-9 select2" name="{$NAME_ATTR}">
		{foreach item=PICKLIST_VALUE key=PICKLIST_NAME from=$PICKLIST_VALUES}
			<option value="{Vtiger_Util_Helper::toSafeHTML($PICKLIST_NAME)}" {if $DEFAULT_VALUE eq $PICKLIST_NAME} selected {/if}>{vtranslate($PICKLIST_VALUE, $SELECTED_MODULE_NAME)}</option>
		{/foreach}
	</select>
```
あたりが怪しいです。
ただ選択肢が空の際に2つ｢オプションの選択｣が出るだけで、選択肢を入れれば普通に動きます。
動作上の問題はほぼないため優先度は低い気がします。
