### ISSUE TITLE
[不具合]送信メールサーバーを設定した際に送られるメールの本文が英語になっている

### ISSUE THREAD

**Issue by kkouta** [thinkingreed-inc/F-RevoCRM#410]
**概要（Overview）**
送信メールサーバーを設定した際に送られるメールの本文が英語になっている

**再現手順（To Reproduce）**
不具合の発生手順を細かく記載してください。
1. dockerにMailHog用のdockerを立て動かす。
2. IPアドレス.記載されているポートを入力しMailHogを開く。
3. F-Revoのシステム設定＞システム構成＞送信メールサーバーを開きサーバー名をmail:1025に設定しメールを送信する。

**スクリーンショット（Screenshots）**
スクリーンショットがあれば添付してください。
（If applicable, add screenshots to help explain your problem.）
![image](https://user-images.githubusercontent.com/95267222/145003706-8ad3eb77-c6b8-4d92-aeee-fa775f03c065.png)

**稼働環境 Server (please complate the following information):**
- OS: [e.g. CentOS8]
- PHP version [e.g. PHP 7.4.11]
- MySQL version [e.g. MySQL 8.0.21]

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: [e.g. Windows10]

**その他情報（Additional context）**

**Comment by Remicck** [comment]
@kkouta 
ありがとうございます。
こちらは、MailHogに対してではなく、送信メールサーバーを変更した際に確認用に送られるメールとなります。
本アプリケーションは日本ユーザーが大半を占めるため、送信メールは日本語に変更できればと思いますので、対応お願いします。
