### ISSUE TITLE
[要望] sql_mode をconfigで指定

### ISSUE THREAD

**Issue by tulistjp** [thinkingreed-inc/F-RevoCRM#42]
**要望とその背景（Request and its background）**

## 要望

config で mysqlのsql_modeを指定できるようなオプションが欲しい。

## 背景

f-revcrmをconoha wing（レンサバ）にインストールするという話になりベンダーに依頼しましたが、conoha wing ではsql_modeを指定することができず、動作確認することができませんでした。

軽く調べたところ、configではmysqliが指定されていたため、ベンダーには下記を参考に修正して動作検証を依頼しましたが、正常に動作しなかったとのことです。
＊SQLモードが公式の推奨と異なるのはベンダーから提示された情報であるためです。
＊私は動作検証環境を持ってないため、机上チェックのみで依頼しています。

libraries/adodb/drivers/adodb-mysqli.inc.php: line 126あたり
```
$ok = $ok && mysqli_query($this->_connectionID,
	"SET SESSION sql_mode='ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'");
```

libraries/adodb/drivers/adodb-pdo.inc.php: line 153あたり
＊こちらは念のため
```
if ('mysql' == $this->dsnType) {
	$this->_connectionID->query("SET SESSION sql_mode='ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'");
}
```

sql自体はphpMyAdminで動作確認済みでエラーなく実行はできていました。

**その他情報（Additional context）**

動作可能な環境を増やすこと自体は御社にもメリットがあるのでは？とも思っております。

是非ご対応いただけますと幸いです。

**Comment by Remicck** [comment]
ありがとうございます。
>config で mysqlのsql_modeを指定できるようなオプションが欲しい。
こちらはレンタルサーバーなどでsql_modeを変更できないようなケースの場合、Queryから設定を変えられるようにしてほしいといった要望で認識あっていますか？

課題としては2つあると思っていて、

**Comment by tulistjp** [comment]
早速のレスと課題の整理、ありがとうございます。

> こちらはレンタルサーバーなどでsql_modeを変更できないようなケースの場合、Queryから設定を変えられるようにしてほしいといった要望で認識あっていますか？

はい。ご認識のとおりです。

ご提示いただいた課題ですが、後者の修正は影響範囲が大きく対応が難しいことは予想しております。
今回の要望は、前者の方法にて解決していただきたいという要望でした。

> もし、@tulistjp の方で対応が進みましたらPRもらえると助かります。

残念ながら、私の方でCRM導入に対して作業することが許可されていない状況でして、修正することができません。

もしご対応いただける場合は、対応時期など分かりますと大変助かります。

---

余談ですが、今回問題となっているのはConohaのWINGというレンサバです。

Conoha WINGではsql_modeのデフォルトは下記の通り設定されています。

```SQL
SHOW VARIABLES LIKE 'sql_mode';
```
![image](https://user-images.githubusercontent.com/33207573/107859321-160ec980-6e7c-11eb-942d-8696865cf713.png)

SESSIONでsql_modeが変更可能であることは確認済みです。

```SQL
SET SESSION sql_mode='ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
SHOW VARIABLES LIKE 'sql_mode';
```
![image](https://user-images.githubusercontent.com/33207573/107859332-24f57c00-6e7c-11eb-91c7-f2dde58e5fcb.png)

**Comment by Remicck** [comment]
@tulistjp 
ありがとうございます。
インストール時の`sql_mode`は`ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`となるように推奨しているので、以下の条件で手元の環境を触ってみました。

- ソースコードはGithubから落としたもの
- `docker/mysql/my.cnf`内の`sql_mode`の箇所はコメントアウト
- `modules/Install/models/Utils.php:364`に`$sqlmdres = $conn->Execute("SET GLOBAL sql_mode='ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';");`を追加

上記状態で、まずインストーラー時点ではコードを修正しない場合sql_modeが異なるとエラーが出ることを確認しています。
コード修正後再度開くと、インストールまでは正常に動かせました。
他の箇所の影響があるかなどはまだ検証できておりませんが、取り急ぎ共有です。

**Comment by Remicck** [comment]
あ、SET GLOBALで対応してしまいました。
SET SESSIONでも動くとは思いますが、選択肢項目作成時のCREATE TABLEなどでどの程度影響があるかは不明です。

**Comment by tulistjp** [comment]
早速ありがとうございます！

頂いた内容はSESSIONでの利用を考えると、インストール時のエラーを回避はできているものの、その後のシステム利用においてはsql_modeの変更はされないので、利用時に何かしらのエラーは発生するかもしれませんね。

PS
私の方でも直接調査してみたい気持ちがあるのですが・・・SESの時間給なもので・・・
ちょっと相談してみます。

**Comment by Remicck** [comment]
@tulistjp 
社内でも話してみたんですが、パフォーマンスの影響を考えるとDBにコネクトする直前全てで、`SET SESSION` するしかないかなぁというところです。
その場合、config.inc.phpから直接毎回呼ぶ（もしくは、PeerDatabase.phpに書き込む）ような感じになりそうという話になったので、少し調べてみます。

ただ、やはりレンサバでの運用は今回の質問内容のような意味で難しい点も多いので、VPSを利用したほうが良いかなぁという感じですね。

**Comment by tulistjp** [comment]
社内での検討、ありがとうございます！
> パフォーマンスはどうしても悪化しますが、DBに繋いだ後全てで、SET SESSION するしかないかなぁというところです。
はい。
レンサバの場合は避けられないだろうなと思っています。
とはいえば、体感できるほどのパフォーマンス劣化はないだろうと予想してます。

> その場合、config.inc.phpから直接毎回呼ぶ（もしくは、PeerDatabase.phpに書き込む）ような感じになりそうという話になったので、少し調べてみます。
調査できないといったものの、軽くだけ調べてました。
おそらく、下記に類似する処理の中で、DB接続している直後にset sessionすればよいのでは？と予想しています。
libraries/adodb/drivers/adodb-xxxxx.inc.php
＊冒頭の「背景」に記載死した内容と絡みます

> ただ、やはりレンサバでの運用は今回の質問内容のような意味で難しい点も多いので、VPSを利用したほうが良いかなぁという感じですね。
なるほどですね。
ベンダーいわく、さくらのレンサバなら実績があるとのことでした。
作り上レンサバの場合はホスティング会社を選ぶというのは仕方がないかもしれませんね。

出来れば、ConohaWINGで運用できればコスト的にも助かるのですが、今回を機にConohaWINGでの稼働実績を作りたいというようなモチベーションがあれば、ご対応いただけますと幸いです。

その際は私の方でも微力ながらサポートさせていただきます。

**Comment by Remicck** [comment]
@tulistjp 
情報ありがとうございます。一応解決できたっぽいので共有です。
実行環境は先日投稿した内容とほぼ同一です。

libraries/adodb/adodb.inc.php:1235
```php
function _Execute($sql,$inputarr=false) {
		// ExecuteCursor() may send non-string queries (such as arrays),
		// so we need to ignore those.
		if( is_string($sql) ) {
			// Strips keyword used to help generate SELECT COUNT(*) queries
			// from SQL if it exists.
			$sql = ADODB_str_replace( '_ADODB_COUNT', '', $sql );
		}

		@$this->_query("SET SESSION sql_mode='ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';", false);

		if ($this->debug) {
			global $ADODB_INCLUDED_LIB;
			if (empty($ADODB_INCLUDED_LIB)) {
				include(ADODB_DIR.'/adodb-lib.inc.php');
			}
			$this->_queryID = _adodb_debug_execute($this, $sql,$inputarr);
		} else {
			$this->_queryID = @$this->_query($sql,$inputarr);
		}
```

私の環境ではクリアできたのでこちらでこのIssueはクローズします。
何かありましたらコメントください。

**Comment by tulistjp** [comment]
内容確認しました。
ご対応いただけたとのことでありがとうございました！

なるほどです。クエリ実行時に都度実行してるんですね。
DB接続時と比較すると効率は悪いけど確実性は高いですね！

さっそくベンダーに動作確認の依頼をかけます。

issueはクローズされていますが、動作結果に関してはご報告させていただきます。
（少し時間かかると思います）

**Comment by Remicck** [comment]
@tulistjp 
ぜひ、最終的な実装の部分ご連絡いただければ幸いです。
よろしくおねがいします。

**Comment by tulistjp** [comment]
@Remicck 
その後の報告です。

ベンダーにこちらのissueを共有し対応してもらったところ、conoha wingでも動作確認が取れました。
ご対応いただき、ありがとうございました。

なお、WINGレンタルサーバーでは `$_SERVER['HTTPS']` がセットされないことにより動作不備があるとのことで、下記を修正したとベンダーより報告があったので共有しておきます。
（修正を依頼したいわけではなく、同じようなところで困っている方がいた場合の情報共有として）

config.inc.php
```PHP
if(isset($_SERVER['HTTP_X_FORWARDED_PROTO']) and $_SERVER['HTTP_X_FORWARDED_PROTO'] === "https") {
    $_SERVER['HTTPS'] = 'on';
}
```

**Comment by Remicck** [comment]
@tulistjp 
レンタルサーバーで動かしたという報告はほぼ初めてなので知見になりました。
※ $_SERVER['HTTPS']についても

報告、ありがとうございます！
