### ISSUE TITLE
[不具合] タグを設定すると、編集内容が反映されない

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#420]
**概要（Overview）**
登録データにタグを設定後、データ編集しても変更内容が反映されない
鉛筆アイコンから編集しても変更内容が反映されない

**再現手順（To Reproduce）**
1. データ登録する
2. データ概要(詳細)画面にて、タグ設定する
3. データを編集し、保存する
4. 編集前の状態に戻る (データ更新されない)
⇒更新履歴にも変更内容が残っていない

**稼働環境 Server (please complate the following information):**
- F-RevoCRM v7.3.5

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- Chrome(96.0.4664.93)

**その他情報（Additional context）**

**Comment by Remicck** [comment]
すみません、 #285 こちらの修正を行ったことによるバグとなります。
暫定対処としては、タグインポートが不可となりますが、以下のコードをコメントアウトしてください。
`data/CRMEntity.php:127`
```php
// tagのテーブルは$table_nameに入ってこないので別途追加
// if($this->column_fields['tags'] != null){
// 	$this->insertIntoTagsTable($module);
// }
```

**Comment by Remicck** [comment]
@Sota-Miyamoto 
この関数がインポート時のみに動くように修正をお願いします。

**Comment by K-Haruto** [comment]
#421 #420
上2件の不具合について、
CRMEntity.php内のinsertIntoTagsTable()関数が**インポート時以外**にも実行されていたために発生していました。

対策について、
インポート時のみ指定の処理が行われるように修正。CRMEntityで処理されている内容は以下の通りであるので、これらの動作確認を行った後PRします。
 - [ ] 新規レコードのインポート
 - [ ] インポートによる既存レコードの更新
 - [ ] 新規作成
 - [ ] クイック作成
 - [ ] 詳細画面から編集
 - [ ] ワークフローからレコード作成
 - [ ] 一括編集
 - [ ] APIから更新
