### ISSUE TITLE
[不具合]タグを複数設定し、データ編集するとタグが増えてしまう

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#421]
**概要（Overview）**
データに「タグ1」「タグ2」のように複数設定し、データ編集すると保存後に「タグ1,タグ2」のタグが追加されてしまう
⇒ ワークフローの「項目の値の更新」が実行されるとさらに「タグ1,タグ2,タグ1,タグ2」が追加されてしまう

**再現手順（To Reproduce）**
不具合の発生手順を細かく記載してください。
（Steps to reproduce the behavior:）
1. データ作成
2. 作成したデータに「タグ1」「タグ2」を設定
3. データ編集し、保存
4. タグが「タグ1」「タグ2」「タグ1,タグ2」になる

**スクリーンショット（Screenshots）**
・手順２
![image](https://user-images.githubusercontent.com/77664240/145791469-1157082c-2507-4a6d-8180-55d6955af554.png)
・手順４
![image](https://user-images.githubusercontent.com/77664240/145791572-ea607a4f-fbf3-473e-8753-a1a6fb5c3835.png)
・ワークフローの「項目の値の更新」が実行された場合
![image](https://user-images.githubusercontent.com/77664240/145792234-77b30e21-4a64-45a9-b6a1-ea09484c6163.png)

**稼働環境 Server (please complate the following information):**
- F-RevoCRM v7.3.5

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- Chrome(96.0.4664.93)

**その他情報（Additional context）**

**Comment by Remicck** [comment]
#420 と同様に、 #285 の修正による影響となります。
こちらはクローズし、420でとまとめて対応します。

ありがとうございました。
