### ISSUE TITLE
[要望]カスタムフィールドを追加する上限を設定してほしい

### ISSUE THREAD

**Issue by masanori** [thinkingreed-inc/F-RevoCRM#424]
**要望とその背景（Request and its background）**

- カスタムフィールドは無制限に追加できてしまうが、DB側の許容量を超えてしまい。
vtiger_fieldとDBのテーブルとの乖離が発生し問題が発生してしまう。

**Comment by Remicck** [comment]
@K-Haruto config.inc.phpなどで可変にできる形で、カスタムフィールドを30を上限とする方向でお願いします。
