### ISSUE TITLE
[要望] 参加者がいる活動で自分だけの活動を削除できるようにしてほしい

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#436]
**要望とその背景（Request and its background）**
参加者がいる活動にて自分が活動に参加できなくなり、自分の活動だけを削除したつもりが、
参加者全員の活動が削除されてしまうため。
⇒ 繰り返し活動の変更・削除のような機能が参加者のいる活動削除にもほしい
![image](https://user-images.githubusercontent.com/77664240/147015551-942e3066-9e17-4643-bfb4-62acd73ae295.png)

**その他情報（Additional context）**

**Comment by kkouta** [comment]
参加者が複数人いる活動にて自分が参加できなくなった場合は、自分だけその活動の参加を解除することができます。
カレンダーにて参加できなくなった活動を選択し参加者の欄から自分を外していただければ大丈夫です。

![image](https://user-images.githubusercontent.com/95267222/156118927-91b60220-accd-400d-afe9-b753ba71336f.png)
