### ISSUE TITLE
[要望]モジュールのアイコンの変更

### ISSUE THREAD

**Issue by junnino** [thinkingreed-inc/F-RevoCRM#45]
**要望とその背景（Request and its background）**
既存のモジュールもしくは作成したモジュールのアイコンを変更したい。
作成したモジュールのアイコンがすべてパズルのピースになるので、差別化を図りたい。

**その他情報（Additional context）**

**Comment by Remicck** [comment]
まずアイコン部分の表示は以下の3条件で出力されています。

1. 画像ファイルが特定の場所にあればそれを表示
1.カスタムモジュール（F-RevoCRM初期インストールではないモジュール）の場合は翻訳後のモジュール名の1文字目を表示 
1.それ以外は事前に用意したフォントセットから、該当のモジュールのものを表示

最終的に管理画面上から変えられるようにすることも視野には入れておりますが、1の方法が最も楽な変更方法になりそうです。

しかし、現状は画像を特定のディレクトリ`/layouts/v7/modules/{$modulename}/${modulename}.png` に置くと表示できるのですが、その場合場所によっては画像のサイズによって適切に表示されません。
上記は修正作業を行う予定ですので少々お待ち下さい。

画像による差し替えが可能であることを確認したらこちらはクローズして、別途要望として置く予定です。
