### ISSUE TITLE
[不具合] メニュー設定における表示バグ

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#458]
**概要（Overview）**
メニュー設定における表示バグが存在する。
また、表示が長いため省略されてしまうところも修正したい

**再現手順（To Reproduce）**
1. システム構成>メニュー設定を選択
2. ツールの項目の「非表示のモジュールを選択」を選択
3. 添付画像のように「LBL_...」が表示される

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/75693720/150261250-d8641819-ab6b-446e-ae7c-df41b146b03a.png)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser chrome

**その他情報（Additional context）**

**Comment by kkouta** [comment]
「LBL_...」が表示されるとのことでしたが、こちらで問題の発生が確認できませんでした。更新ボタンなどでキャッシュを削除した後もう一度ご確認いただけますでしょうか？
　表示が省略されてしまう問題も横幅が十分にある場合は省略されないように修正させていただきます。
