### ISSUE TITLE
[不具合]スケジューラが周期設定通りに実行されない

### ISSUE THREAD

**Issue by hrtkz** [thinkingreed-inc/F-RevoCRM#465]
**概要（Overview）**
スケジューラで「ステータス：有効」「周期：00:15」と設定してあるにもかかわらず、スケジュール通り実行されません

**再現手順（To Reproduce）**
Linux (Ubuntu 22.04)上の Docker 環境で動作させています。

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/2147344/150641724-bf03a685-6b03-4786-b89b-097d7454b484.png)
15分周期で動作するはずのタスクが30分経過しても動作していません。
スクリーンショットで最終開始日時が記録されているのは、手動で、sh vtigercron.sh　を実行したためです。

**稼働環境 Server (please complate the following information):**
- Ubuntu 22.04
git clone https://github.com/thinkingreed-inc/F-RevoCRM.git にて取得した docker-compose.yml にて起動しています。

**その他情報（Additional context）**
docker コンテナ内にはいり、sh vtigercron.sh　を実行することで、最終開始日時、最終終了日時が表示されます。

```
docker exec -it f-revocrm_php_1 /bin/bash                                                                                                                                                                                 
root@8fb12ace41ec:/var/www/html# sh vtigercron.sh
root@8fb12ace41ec:/var/www/html# cd cron
root@8fb12ace41ec:/var/www/html/cron# sh vtigercron.sh
[CRON],"1642860838.929",http://f-revocrm:8190/,Instance,"2022-01-22 23:13:58","",[STARTS]
[CRON],"1642860838.929",http://f-revocrm:8190/,Workflow,"2022-01-22 23:13:58","",[STARTS]
以下略
```
もし、docker コンテナで実行するときに cron を動作させるには特別な設定があればその方法を教えてくださると助かります。

**Comment by Remicck** [comment]
@hrtkz 
ご連絡遅くなってしまい申し訳ございません。
dockerでcronを動かす方法は私の方では行ったことがなくご回答できないのですが、ホストマシンのcrondから、`docker exec`を使って、cron/vtigercron.shを叩いていただければ定期実行は可能です。
