### ISSUE TITLE
ワークフローからのメール送信時のURLについて

### ISSUE THREAD

**Issue by TakamatsuKeita** [thinkingreed-inc/F-RevoCRM#478]
**質問内容（Contents of question）**
ワークフロー機能のメール送信にて、「登録データのURL」を選択した際に生成されるリンクのURLが、
`https://example.jp//index.php?*****`　となっており、ドメインの後ろに「/]」が二重で入る動きとなっています。

こちら実影響は今のところ出ておりませんが、閲覧環境によってURLリンクが正常に機能するか懸念です。
この現象（スラッシュが２つ入る）は仕様でしょうか？

**Comment by Remicck** [comment]
@TakamatsuKeita 
上記サイトURL部分は `config.inc.php`の`$site_URL`の値が使われます。
こちらのURLを `https://example.com/crm` と、最後に / を入れない形で登録してください。
