### ISSUE TITLE
[不具合]ダッシュボードのウィジェットのノートで、URLを記入し保存すると ?以降が切り取られてしまう

### ISSUE THREAD

**Issue by masanori** [thinkingreed-inc/F-RevoCRM#48]
**概要（Overview）**
1. ダッシュボードのウィジェットのノートで、URLを記入し保存すると ?以降が切り取られてしまう

**再現手順（To Reproduce）**
1. ダッシュボード＞ウィジェットの追加＞ノートを選択
2. ノートを編集
3. 下記リンクを記入すると?移行が切り取られてしまう
4. `https://****/index.php?module=Reports&view=Detail&record=284
→
https://****/index.php`

**スクリーンショット（Screenshots）**

- なし

**稼働環境 Server (please complate the following information):**
- OS: CentOS
- PHP version ?
- MySQL version ?

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: [Windows10]
- Browser [chrome]
- Version [88]

**その他情報（Additional context）**

**Comment by Remicck** [comment]
ありがとうございます。再現しました。
7.3.3目処に対応予定です。
