### ISSUE TITLE
新規作成時の「担当」のデフォルト値について

### ISSUE THREAD

**Issue by TakamatsuKeita** [thinkingreed-inc/F-RevoCRM#484]
**質問内容（Contents of question）**
各モジュールの新規作成について、「担当」は必須項目となっており、ログインユーザーがデフォルト値でセットされる動作となっています。利用者が新規作成時に意識して「担当」に変更を加えない限り、正しい担当者をセットしないまま「担当：ログインユーザー」にて作成できてしまいます。

このデフォルト値を空欄にしない限り、必須項目チェックの対象にならないと思いますが、新規作成時の「担当」のデフォルトを空欄をデフォルト値とすることは不可能でしょうか。

**Comment by Remicck** [comment]
@TakamatsuKeita 
担当項目はご指摘の通りログインユーザーがデフォルトで設定される仕様になっています。

空欄をデフォルトにするにはソースコード自体を修正しなくてはいけませんが、「担当」の項目はすべてのモジュールに存在する項目になりますので、影響範囲はかなり広めです。

**Comment by Remicck** [comment]
@TakamatsuKeita 
`layouts/v7/modules/Vtiger/uitypes/Owner.tpl`
25行目から
```
{if $FIELD_VALUE eq ''}
	{assign var=FIELD_VALUE value=$CURRENT_USER_ID}
{/if}
```
この部分について、新規作成の場合は`$FIELD_VALUE`が空になるため、ログインユーザーのIDが`$FIELD_VALUE`として変数に代入され、
36行目からの
```
{foreach key=OWNER_ID item=OWNER_NAME from=$ALL_ACTIVEUSER_LIST}
							<option value="{$OWNER_ID}" data-picklistvalue= '{$OWNER_NAME}' {if $FIELD_VALUE eq $OWNER_ID && $VIEW_SOURCE neq 'MASSEDIT'} selected {/if}
```
にて、
`{if $FIELD_VALUE eq $OWNER_ID && $VIEW_SOURCE neq 'MASSEDIT'} selected {/if}`
上記のように
選択肢の`$OWNER_ID`と`$FIELD_VALUE`が一致していて、`$VIEW_SOURCE` がMASSEDITでない場合、選択済みになります。

ですので、`selected`にする条件を変更することで、選択済みにしない挙動は可能かと思われます。
