### ISSUE TITLE
[要望]リスト作成後に項目名を変更した項目もリストの編集・複製時に引き継がれるようにしてほしい

### ISSUE THREAD

**Issue by ayako-hira** [thinkingreed-inc/F-RevoCRM#495]
**要望とその背景（Request and its background）**
リストに選択した項目名をリスト作成時と異なるものに変更してしまうと、編集・複製時該当項目が引き継がれず表示されない

**その他情報（Additional context）**

**Comment by Remicck** [comment]
@ayako-hira 
こちらはラベル自体の更新の場合に発生するという不具合と認識しました。

@K-Haruto 
DBでfieldlabelを直接変更すると不具合が再現します。こちらで確認お願いします。

**Comment by K-Haruto** [comment]
@Remicck 
vtiger_fieldのfieldlabelを直接変更することで不具合を確認しました。

リストに表示されない原因について、
vtiger_cvcolumnlistに各リストの項目が登録されており、このテーブルが変更されないため発生していました。

修正方針は以下を目指します。
  * vtiger_cvcolumnlistの情報とvtiger_fieldの情報を比較し、vtiger_fieldのfieldlabelを優先するようにする
