### ISSUE TITLE
[不具合]ドキュメントのダウンロードができない

### ISSUE THREAD

**Issue by x7dec** [thinkingreed-inc/F-RevoCRM#5]
**概要（Overview）**

ドキュメントのシステム内部にアップロードを実行したファイルがダウンロードができない

**再現手順（To Reproduce）**

1. ドキュメントを開く
2. 新しいドキュメント→システム内部
3. 適当なファイルをアップロード
4. リストのファイル名をクリックしてもエラーになる

**スクリーンショット（Screenshots）**

![image](https://user-images.githubusercontent.com/53038605/101317122-367d3f00-38a1-11eb-9c2e-106ea75b46de.png)

**稼働環境 Server:**
- OS:  CentOS7
- PHP version . PHP 7系

**不具合発生時の利用ブラウザ Blowser:**
- OS:  Windows10
- Browser chrome

**その他情報（Additional context）**

**Comment by Remicck** [comment]
ありがとうございます。
原因はstorageディレクトリが.gitignoreで消されている為なので、.gitignoreの範囲を適切に設定して修正します。
