### ISSUE TITLE
［質問］WEBフォームから取り込まれた複数選択肢の区切り記号について

### ISSUE THREAD

**Issue by TakamatsuKeita** [thinkingreed-inc/F-RevoCRM#515]
**質問内容（Contents of question）**
WEBフォームから問合せデータを受信した際に、システムのワークフローアクションで「受付完了メール」を送付しています。
WEBフォーム内で「選択肢（複数）」の項目にて２つ以上の選択肢を選択して送信すると、

【選択肢１】|##|【選択肢２】　

上記のような形で選択肢が区切られてDBの　vtiger_leadscf　テーブル内に取り込まれています。
この項目をワークフローのメールアクションで項目追加し、送信するとvtiger_leadscfの該当項目値のまま上記のように区切られた形でそのままメール送付されます。これがメール文面上、文字化けや正しくない表記として伝わってしまっています。

この区切り記号　”|##|”　はシステム画面上で表記されているように　”,”　などの、区切りと分かりやすい記号に変更することは可能なのでしょうか。

**Comment by Remicck** [comment]
@TakamatsuKeita 
ありがとうございます。
メール送信時に`|##|`が表示されるのはバグとなりますので修正します。

内部的に`|##|`を別の記号にするのは影響範囲が広いので避けたいと思っておりますが、メール送信周りで修正されれば問題ないでしょうか。

**Comment by TakamatsuKeita** [comment]
> @TakamatsuKeita ありがとうございます。 メール送信時に`|##|`が表示されるのはバグとなりますので修正します。
> 
> 内部的に`|##|`を別の記号にするのは影響範囲が広いので避けたいと思っておりますが、メール送信周りで修正されれば問題ないでしょうか。

@Remicck 
早速のご確認を頂き、誠にありがとうございます。
ワークフローのメール送信時に、`|##|`のように選択肢の区切りと判別しづらい状態で送信されなければ問題ありません。
ご対応の程何卒宜しくお願い致します。

**Comment by Remicck** [comment]
@K-Haruto 
ワークフローからメール本文を作成する処理で、複数選択肢の場合にはglueとなる `|##|`を`,`に置換するコードをお願いします。
タイトル部分とかにも影響するかもしれないのでその点注意してもらえると。

**Comment by Remicck** [comment]
@K-Haruto 
ここで直りそうです。
`modules/com_vtiger_workflow/VTSimpleTemplate.inc:310`

```php
case 'multipicklist' :  require_once 'includes/runtime/LanguageHandler.php';
	require_once 'includes/runtime/Globals.php';
	$fieldValueParts = explode('|##|',$fieldValue);
	foreach($fieldValueParts as $index=>$fieldValue) {
		$fieldValueParts[$index] = vtranslate($fieldValue,$moduleName,$ownerObject->column_fields['language']);
	}
	$fieldValue = implode(',', $fieldValueParts);
	break;
```

explodeで分割する文字が悪そうです。
