### ISSUE TITLE
[不具合]見積の住所情報の関連選択時に出るエラーメッセージの内容が仕様と合っていない

### ISSUE THREAD

**Issue by ayako-hira** [thinkingreed-inc/F-RevoCRM#527]
**概要（Overview）**
見積の住所情報の関連選択時に出るエラーメッセージの内容が仕様と合っていない

**再現手順（To Reproduce）**
1. 見積モジュール＞住所情報＞関連にチェックを入れる
2. 「住所コピー元のリードまたは顧客担当者を選択してください」というエラーが出る
3. リードからは住所をコピーすることが出来ないため、エラーの文章がおかしい

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/81276456/168196066-727b9014-e907-46ed-96bf-f4829931ae05.png)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: [Windows10]
- Browser [chrome]

**Comment by K-Haruto** [comment]
@Remicck 
本件のバグの内容は以下になります。チェックボックスは修正する内容です。

1. 「関連」で参照されるのは`ご担当者様名`である(下画像)
    * 初期インストール時は「ご担当者様名」項目として見積作成画面に表示される。
    * `ご担当者様` = `顧客担当者`であり、エラーメッセージは正しい。
    - [ ] ご担当者様名ではなく顧客担当者と表示させるようにする
![image](https://user-images.githubusercontent.com/75693720/169930027-e9729a5e-8f35-4312-8593-afd97b733efa.png)

2. 見積>ご担当者様名の項目を削除することができる
    * 項目を削除されなければ見積作成画面に表示されるが、削除されると見積画面に表示されなくなる→参照元が無くなる
    - [ ] 項目が無くなった場合、作成画面から関連を非表示にする
![image](https://user-images.githubusercontent.com/75693720/169930808-2f12b059-5b7d-4e30-b2ac-714967e367b6.png)
