### ISSUE TITLE
タスクを個人カレンダー画面上部からショートカットで完了できるようにしてほしい

### ISSUE THREAD

**Issue by mozukuudon** [thinkingreed-inc/F-RevoCRM#543]
**要望とその背景（Request and its background）**
タスクをすぐに完了にできないことが少し不便に思いました。
活動のように、予定にカーソルを合わせるとポップアップから完了等の操作ができるようにしていただきたいです。

**その他情報（Additional context）**

**Comment by kkouta** [comment]
#354 こちらの修正にて対応させていただきました。

**Comment by Remicck** [comment]
#354 で対応しましたのでCloseします。
