### ISSUE TITLE
[不具合]カスタム項目の関連として「カレンダー」もしくは「活動」を追加するとテキストとして保存される

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#562]
**概要（Overview）**
カスタム項目の関連として「カレンダー」もしくは「活動」を追加するとテキストとして保存される。
また、この項目をモジュールの編集画面から設定しようとすると権限エラーが発生する。

**再現手順（To Reproduce）**
(例)
1. 顧客担当者のカスタム項目として「活動」を登録する→テキストとして保存される
2. 顧客担当者の編集画面を開き、登録した項目を編集する→権限エラーが発生する

**スクリーンショット（Screenshots）**
* カスタム項目編集画面
![image](https://user-images.githubusercontent.com/75693720/173492083-ca98337f-f202-437a-a382-28aed7405a16.png)
* 保存後
![image](https://user-images.githubusercontent.com/75693720/173492108-390efa90-8d68-43c9-9959-4bd7555a7c04.png)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser chrome

**その他情報（Additional context）**

**Comment by kkouta** [comment]
@Remicck 
顧客担当者の項目で関連を持つ必要はあるのでしょうか？顧客担当者を選択すると下図のようにすでに関連項目が表示されている状態だと思うます。カスタム項目に関連を選択できないようにする修正が妥当なのかなと感じました。
![image](https://user-images.githubusercontent.com/95267222/186634670-36a3bf7c-ae00-4b23-8ecc-76a7a1d5e59c.png)

**Comment by Remicck** [comment]
@K-Haruto  @kkouta 
関連項目として、活動・カレンダーは設定できないようにしてください。
※利用用途が少ないですし、上の例での顧客担当者モジュールの場合、すでにあったりと不要と考えます。
