### ISSUE TITLE
[不具合] 共有カレンダーにて、予定をマウス移動すると非表示にしていたユーザーの予定も表示される

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#574]
**概要（Overview）**
共有カレンダーにて、予定をマウス移動すると非表示にしていたユーザーの予定も表示されてしまう

**再現手順（To Reproduce）**
不具合の発生手順を細かく記載してください。
（Steps to reproduce the behavior:）
1. 共有カレンダーにて、サイドバーに表示されるユーザーのチェックボックスを外す(下画像ではuser2が外れている)
![image](https://user-images.githubusercontent.com/75693720/176109962-94ad0d45-0bf5-4886-af31-7881549b6ec2.png)
2. 予定をマウス移動する
　→外したはずのチェックボックスに✓が入り、user2の予定が表示されるようになる

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser chrome

**その他情報（Additional context）**
#549 の修正中に発見

**Comment by Sota-Miyamoto** [comment]
調査したところ、layouts\v7\modules\Calendar\resources\Calendar.jsのrestoreFeedsState関数において、disabledFeedsの値がおかしいようです。
同ファイルのenableFeed関数、disableFeed関数で無効なカレンダーをうまく記録できていない可能性が高いです。
