### ISSUE TITLE
[不具合]Excelファイルをアップロードした場合、vtiger_notesのfiletypeの桁数が足りていない

### ISSUE THREAD

**Issue by hasesho28** [thinkingreed-inc/F-RevoCRM#578]
**概要（Overview）**
掲題の通り

**再現手順（To Reproduce）**
任意のモジュールにドキュメントとしてExcelファイル（.xlsx）を添付する。

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/84055994/177951026-92119588-784c-4167-8a0c-4b438812f739.png)
![image](https://user-images.githubusercontent.com/84055994/177951069-1e767cc9-4bd6-45c1-a4d4-901c0c8b11f6.png)

**稼働環境 Server (please complate the following information):**
環境依存ではないと思われるため省略

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
ブラウザ依存ではないと思われるため省略

**その他情報（Additional context）**
filetypeにはMIMEタイプが保存されるが、.xlsxファイルの「application/vnd.openxmlformats-officedocument.spreadsheetml.sheet」を保持するには桁数が50桁では足りていない。
MIMEタイプの桁数がRFCなどで定められているのであれば、調査および必要な桁数を検討し、拡張してほしい。

**Comment by Remicck** [comment]
@K-Haruto 
桁数自体調査してもらいたいですが、明確な定義がなければvarchar(255)としてください。
Migrationツールで型を変える感じでお願いします。

**Comment by kkouta** [comment]
> @K-Haruto 桁数自体調査してもらいたいですが、明確な定義がなければvarchar(255)としてください。 Migrationツールで型を変える感じでお願いします。

MIMEタイプの桁数を明確に定めているところはありませんでした。
以下にMIMEタイプの一覧が載っていますが、その中だと一番長いもので84でした。今回は255桁で修正させていただきました。現状filetypeの桁数は100でも足りると思います。
https://www.iana.org/assignments/media-types/media-types.xhtml
