### ISSUE TITLE
[要望]見積等のPDFを出力した際のファイル名に項目の値を指定したい

### ISSUE THREAD

**Issue by ayako-hira** [thinkingreed-inc/F-RevoCRM#580]
**要望とその背景（Request and its background）**
PDFを出力すると全て同じ「テンプレート名」で出力されるため、ファイル名を変更する必要がある。
ファイル名を例えば「見積書-[案件名][見積番号]」のような形で出力できるようにしたい。

**Comment by junmt** [comment]
$pdffilename = Vtiger_InventoryPDFController::getMergedDescription($recordModel->get("pdffilename"), $recordId, $moduleName);
ってな感じで現状でも変数を入れておけばPDFのファイル名に出力元の番号やタイトルを入れることができます。
なので、このIssue自体不要と考えます。
