### ISSUE TITLE
[不具合]契約モジュールの関連で表示されるチケットアイコンの名称が「サービスリクエスト」と表示される

### ISSUE THREAD

**Issue by suzuki-y2** [thinkingreed-inc/F-RevoCRM#610]
**概要（Overview）**
契約モジュールの関連で表示されるチケットアイコンにカーソルを合わせるとの名称が「サービスリクエスト」と表示される

**再現手順（To Reproduce）**
1.契約モジュールのレコードを開く
2. 関連で表示されるチケットアイコンにカーソルを合わせる

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/108853236/184788137-5752e871-66e2-43f5-a186-a13613d740d8.png)

**Comment by Remicck** [comment]
@K-Haruto 
`vtiger_relatedlists.label` の中身がその様になっているため、`languages/ja_jp/Vtiger.php` で翻訳されている状況です。

ここはチケットがそのまま表示されるので、HelpDesk（→チケットとなるよう）に変更するMigrationのスクリプトをお願いします。
一旦11月パッチ想定です。
