### ISSUE TITLE
[不具合]メールの「クリック数」のカウントが動作していない

### ISSUE THREAD

**Issue by ayako-hira** [thinkingreed-inc/F-RevoCRM#629]
**概要（Overview）**
モジュールの関連タブにある「メール」一覧に表示される「カウント」が動作していない

**再現手順（To Reproduce）**
不具合の発生手順を細かく記載してください。
（Steps to reproduce the behavior:）
1. F-RevoからURL付きのメールを送信
1. 届いたメールのURLをクリック
1. カウントの数字が動かない

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/81276456/188339885-23a3e83b-b054-4f08-b3cf-9c08bf968149.png)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser chrome

**Comment by Remicck** [comment]
@kkouta 
config.inc.phpにemail_tracking = 'Yes'を設定すると、アクセス数は取れそうです。

**Comment by kkouta** [comment]
config.inc.phpのemail_tracking = 'Yes'を設定するとアクセス数、クリック数ともに確認できました。
![image](https://user-images.githubusercontent.com/95267222/190554546-52112f5c-8d56-4486-ab1a-58ddce890d3a.png)

動作としては下記に記載します。

1.	Shorturl.phpからShortURL.phpのVtiger_ShortURL_Helperクラスのhandleメゾットが呼び出される。
2.	メールのurlに添付されたidを元にvtiger_shorturlsから呼び出すファイルとクラス、添付されたurlなどの情報を取得する。
3.	2で取得した情報を元にclickHandlerとopenHandlerを実行する。
4.	clickHandlerは添付されたurlをクリックしたときに実行され、trackClicks関数によってvtiger_email_trackにクリック数を保存・更新していく。
5.	openHandlerはメールを開いたときに実行され、最後のアクセスから一時間以上経過した時のみアクセスとしてカウントしvtiger_email_trackにアクセス数を保存・更新していく。

**Comment by Remicck** [comment]
@yutakoseki 
インストール時に`config.inc.php`が生成される際に、上記コンフィグを生成するようにしてください。
