### ISSUE TITLE
[不具合]ユーザー管理の名称が「ユーザ」で表示される

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#63]
**概要（Overview）**
ユーザー管理の名称が「ユーザ」で登録されている

**再現手順（To Reproduce）**
1. ユーザー管理をクリックする

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/75693720/110298782-53f4ad00-8038-11eb-9847-10d1f98d5105.png)

**稼働環境 Server (please complate the following information):**

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
OS: Windows10
Browser: chrome

**その他情報（Additional context）**

**Comment by pavish69** [comment]
#213 で対応するためクローズします。
