### ISSUE TITLE
[不具合]メールテンプレートの選択について

### ISSUE THREAD

**Issue by Bana8** [thinkingreed-inc/F-RevoCRM#651]
**概要（Overview）**
リストからメールを一斉送信する際に「メールテンプレートの選択」ボタンを押下しても反応がない。

**再現手順（To Reproduce）**
1. 顧客担当者＞顧客担当者リスト 
2. チェックボックスを複数（名）選択
3. その他>メールを送る
4. メール作成画面で「メールテンプレートの選択」をクリックしても反応しない

**スクリーンショット（Screenshots）
![image](https://user-images.githubusercontent.com/88866510/193514300-5d216f63-a7c2-43af-bf5e-e7c30f798abb.png)
![image](https://user-images.githubusercontent.com/88866510/193514474-ccffa309-0992-4121-921b-bc5b43547897.png)

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
-Googlechrome

**Comment by Remicck** [comment]
#668
こちらは上記PRにて対応しましたので、Closeします。
