### ISSUE TITLE
[要望]日付の項目を作成する際、デフォルト値にその日の日付を設定したい

### ISSUE THREAD

**Issue by junnino** [thinkingreed-inc/F-RevoCRM#70]
日付のデフォルト値には決まった日付しか指定できないため、常に本日の日付をデフォルト値に設定するようにしたい。

**Comment by kkouta** [comment]
修正の方針について
・カスタム項目のデフォルト値にvtiger_todayなど今日を表す単語をボタンから保存できるようにする。
・新しいレコードを作成するときに、valueにvtiger_todayが渡されてきたらjs側で今日の日付に直すようにする。
上記の方法で修正する場合、valueに文字列を許容する必要がある。そのため誤った日付形式で保存された場合に正しく保存できない可能性があるため、解決策を模索中である。
