### ISSUE TITLE
[不具合]iPadで画面回転させると高さ方向が適切に表示されないケースが有る

### ISSUE THREAD

**Issue by Remicck** [thinkingreed-inc/F-RevoCRM#71]
**概要（Overview）**
iPadの画面表示において個人カレンダー表示などで、F-revo6.5環境では、縦、横に画面を切り替えても正しく表示されるのですが、FrevoCRM7.3環境では、縦表示では画面下4/5くらいが黒く表示されて正しく表示されません。

**再現手順（To Reproduce）**
画面のRotate

**スクリーンショット（Screenshots）**
スクリーンショットがあれば添付してください。
（If applicable, add screenshots to help explain your problem.）

**稼働環境 Server (please complate the following information):**
- iPad

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: [e.g. Windows10]
※報告の記載のため、手動で確認次第記載します。

**その他情報（Additional context）**

**Comment by Sota-Miyamoto** [comment]
widthが769pxから991pxで発生
恐らく以下のiPadのみで発生する
 * iPad(7世代)
 * iPad Pro 10.5
 * iPad Air(3世代) 
 * iPad Air(4世代) 
 * iPad Pro 11

**Comment by Sota-Miyamoto** [comment]
#49 のプルリクエストで追加で修正

**Comment by Remicck** [comment]
こちらは黒くはなりませんでしたが、iPad等で適切に表示されない不具合を解消しましたのでCloseします。
同様の現象が発生した場合、再度起票します
