### ISSUE TITLE
[不具合]MailConverter.pngが日本語翻訳されていない

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#72]
**概要（Overview）**
メールコンバータのMailConverter.pngが日本語翻訳されていない

**再現手順（To Reproduce）**
1. 設定>システム設定を開く
2. 自動化>メールコンバータを開く

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/75693720/111112137-f9f96780-85a2-11eb-8987-7eef6d2e1072.png)

**稼働環境 Server (please complate the following information):**

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser: chrome

**その他情報（Additional context）**

**Comment by Remicck** [comment]
2c123600eb1b1dca3e3605354d6b757df1e308d3
対応しました
