### ISSUE TITLE
[不具合]DB上の名前の最後にスペースが隠れている

### ISSUE THREAD

**Issue by K-Haruto** [thinkingreed-inc/F-RevoCRM#73]
**概要（Overview）**
vtiger_projecttaskstatusテーブルにある"Canceled"が"Canceled[スペース]"で登録されている。

**再現手順（To Reproduce）**
1. プロジェクト>タスク>プロジェクトタスクの新規作成
2. 基本情報のステータスのメニューを表示する

**スクリーンショット（Screenshots）**
![image](https://user-images.githubusercontent.com/75693720/111130053-1d7bdc80-85ba-11eb-84ab-4ba6cce4a0a7.png)

**稼働環境 Server (please complate the following information):**

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser: chrome

**その他情報（Additional context）**

**Comment by Remicck** [comment]
対応済みなのでCloseします。
