### ISSUE TITLE
[不具合] IE11でエクスポートすると文字化けしてしまう

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#76]
**概要（Overview）**
IE11のブラウザで、顧客企業や案件等のデータをエクスポートするとファイル名が文字化けしてしまう。

**再現手順（To Reproduce）**
1. 顧客企業の一覧表で、CSV出力したいデータを選択
2. その他> エクスポートから手順1で選択したデータをエクスポートする
3. ファイル名が「(文字化け).csv」になってしまう
⇒ エクスポートしたデータは文字化けしていないです。

**スクリーンショット（Screenshots）**

**稼働環境 Server (please complate the following information):**
- OS: [CentOS7]
- PHP version [PHP 7.2.18]
- MySQL version [MySQL 8.0.16]
- F-RevoCRM version7.3.2

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: [Windows10]
- Browser [Internet Explorer11]
- Version [11.778.18362.0]

**その他情報（Additional context）**

**Comment by Remicck** [comment]
@gatty2672 
Edge, Chromeでは再現しない不具合かわかりますか？

**Comment by gatty2672** [comment]
@Remicck 
Edge、Chrome、Firefoxでは再現しませんでした。

**Comment by Remicck** [comment]
@gatty2672 IE11で試しましたが、再現しませんでした。
以下確認してもらえますか？

- F-RevoCRMの最新版か
- 互換性モードとなっていないか

よろしくおねがいします。

**Comment by gatty2672** [comment]
@Remicck 
- F-RevoCRMの最新版か
F-RevoCRM version7.3.2です。

- 互換性モードとなっていないか
互換性モードにはなっていないです。

**Comment by Remicck** [comment]
@gatty2672 
再現しました、確認しますありがとうございました。

**Comment by Remicck** [comment]
IE11サポート対象外として、クローズします。
