### ISSUE TITLE
[不具合]翻訳が掛かっている選択肢項目のエクスポート、インポートについて

### ISSUE THREAD

**Issue by amino1205** [thinkingreed-inc/F-RevoCRM#767]
**概要（Overview）**

　①翻訳が掛かっている選択肢項目をエクスポートすると英語で出力される
　②翻訳が掛かっている選択肢項目を日本語でインポートするとフィルターの条件が一致していても一覧に表示されない

**再現手順（To Reproduce）**

①-1 案件.営業ステージに値が入っているレコードをエクスポート
①-2 エクスポートデータが英語で出力される

②-1 案件の一覧で営業ステージ　等しい　発掘　のリスト作成
②-2 案件.営業ステージに「発掘」を入れたインポート用csv作成
②-3 上記データを案件にインポート
②-4 ②-1で作成されたリストに②-3で入れたデータが出てこない

**その他情報（Additional context）**

対応方法
①　エクスポート時に翻訳処理を入れる
②　インポート時選択肢項目は以下処理を入れる
　　　・選択肢翻訳前後を取得
　　　・入力項目の翻訳語があったら翻訳前の値を入れる
　　例外部分
　　　・言語設定が日本語である場合は英語で入れられたものは選択肢に無い扱いで良い

**Comment by Remicck** [comment]
@kento-yn @kkouta 
1月中に修正が終わると助かります・・・！
