### ISSUE TITLE
[不具合] リストで日付項目に「空である」を指定するとSQLエラーが発生する

### ISSUE THREAD

**Issue by junmt** [thinkingreed-inc/F-RevoCRM#768]
**概要（Overview）**
リストで日付項目に対して「空である」「空ではない」を指定するとリスト表示時にSQLエラーが発生する

**再現手順（To Reproduce）**
1. 顧客企業に任意の日付項目を追加
1. 顧客企業のレコードを追加（上記の項目は空にしておく）
1. 顧客企業のリストを追加（条件：上記項目を「空である」）
1. 追加したリストを表示する
1. リストに登録したレコードが表示されない（debugログを見るとSQLエラーが発生している）

**稼働環境 Server (please complate the following information):**
- MySQL 8.0
※MySQL 8.0未満では発生しないはず（未確認）

**その他情報（Additional context）**
SQLを生成する際に「= ''」が含まれており、MySQL8.0からは日付型に対して指定するとエラーになる。

**Comment by junmt** [comment]
pull request送ろうと思ったら、変なファイル差分が出てきてしまったので誰か代わりにお願い。
https://github.com/junmt/F-RevoCRM/commit/b6cc641a2a16fdf6bcf34b32fea02a03ae92235e

**Comment by junmt** [comment]
現在も再現するか要確認

**Comment by K-Haruto** [comment]
@junmt 

#828 にて該当部分の修正が適用されていたため、現在のmainでは再現しませんでした。
