### ISSUE TITLE
[不具合]フィルターのデフォルト設定の不具合

### ISSUE THREAD

**Issue by Remicck** [thinkingreed-inc/F-RevoCRM#78]
**概要（Overview）**
個人リストにフィルターを追加して、デフォルト設定すると、操作で別フィルターを設定していても
ログインしなおして画面表示すると、デフォルトに設定したフィルターが設定されます。

共有リスト(他ユーザーで作成)のフィルターをデフォルトに設定すると、操作で別フィルターを設定して
ログインしなおして画面表示すると、デフォルトに設定したフィルターになりません。

**再現手順（To Reproduce）**

**スクリーンショット（Screenshots）**

**稼働環境 Server (please complate the following information):**
- F-RevoCRM v7.3.2

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**

**その他情報（Additional context）**
v6.5では、自ユーザーで作成したフィルターや、公開・その他のフィルターのどのフィルターでデフォルト設定してもログイン後の初期表示はデフォルトに設定したフィルターで絞り込まれます。

**Comment by K-Haruto** [comment]
共有リストをデフォルトに設定する際、
そのリストの作成者以外はリストの編集画面を開けないため、**リスト右横のデフォルトチェックボックス**からデフォルトの設定を行わなければいけません
![image](https://user-images.githubusercontent.com/75693720/113657519-12a7f980-96d9-11eb-8c1e-fa04a8b96576.png)
このチェックボックスに不具合があるため指摘された現象が生じているのだと考えられます。

したがって、修正すべき内容は以下になります。
- チェックボックスが複数選択できてしまう
→ 最後にデフォルト設定したリスト以外のチェックボックスから✓を外す
- 共有リスト作成者がその共有リストをデフォルトに設定した際, 他のユーザーのチェックボックスにも✓が入ってしまう
→ 他ユーザーには✓が入らないようにする
