### ISSUE TITLE
[不具合] システム設定でキーワードの詳細検索を行うと、エラーメッセージが表示される

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#80]
**概要（Overview）**
システム設定(ユーザの管理や項目編集 等)でキーワードの詳細検索「Ⓥ」ボタンを押すと、
「権限がありません」のエラーメッセージが表示される。

**再現手順（To Reproduce）**
1. 管理者ユーザで、画面左上の「三」> 設定> 「システム設定」を開く
2. 画面上部にある「キーワード検索」の「Ⓥ」ボタンを押す
3. 「権限がありません」のエラーメッセージ(下記スクリーンショット)が表示される

**スクリーンショット（Screenshots）**
![#80](https://user-images.githubusercontent.com/77664240/111428313-aae63a80-873a-11eb-9ef0-264c2ecffe2a.png)

**稼働環境 Server (please complate the following information):**
- OS: [CentOS7]
- PHP version [PHP 7.2.18]
- MySQL version [MySQL 8.0.16]
- F-RevoCRM version7.3.2

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: [Windows10]
- Browser [chrome]
- Version [88.0.4324.190]

**その他情報（Additional context）**

**Comment by gatty2672** [comment]
上記ですが、一般ユーザの「個人設定」でも再現しました。
システム設定でキーワードの詳細検索を行うとエラーメッセージが表示されるようです。

**Comment by Sota-Miyamoto** [comment]
モジュールがsettingsのとき，searchableModulesParamsのmoduleNameをHomeとすることでエラーは起こらなくなりました．(AdvanceSearch.js)
ただHomeモジュールで検索した際に検索ボタンが押せなくなる不具合があり，まだ検索を機能させられていないです．
![image](https://user-images.githubusercontent.com/53038605/111972418-ca1d0780-8b40-11eb-9d5d-fd4dcd572a1b.png)
