### ISSUE TITLE
[不具合]DBのmigrationが実行されない

### ISSUE THREAD

**Issue by tnaka176** [thinkingreed-inc/F-RevoCRM#851]
**概要（Overview）**
v7.3.6からv7.3.8にmigrationを行いましたが、DBのマイグレート処理が実行されませんでした。

**稼働環境 Server (please complate the following information):**
- Docker 23.0.3
- PHP php:7.4.33-apache
- MySQL mariadb:10.7.4-focal

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows10
- Browser Firefox
- Version 102.12.0esr(64bit)

**その他情報（Additional context）**

以下のように修正すると実行されました。

* modules/Migration/models/Module.php

```
--- Module.php.orig     2023-06-28 09:22:01.598514070 +0900
+++ Module.php  2023-06-28 09:22:53.498515691 +0900
@@ -52,6 +52,8 @@
                        array('734' => '7.3.4'),
                        array('735' => '7.3.5'),
                        array('736' => '7.3.6'),
+                       array('737' => '7.3.7'),
+                       array('738' => '7.3.8'),
                );
                return $versions;
        }
```

**Comment by junmt** [comment]
@kkouta 
vtigerversionを「7.3.8.1」にしてマイグレーションが実行できるように修正してほしいです。
（7.3.8はリリース済みのため、バージョンを上げないといけない）
