### ISSUE TITLE
[質問]入力値の長さチェックについて

### ISSUE THREAD

**Issue by hiroshih** [thinkingreed-inc/F-RevoCRM#857]
**質問内容（Contents of question）**
初期状態からある「顧客担当者」の「部署」カラムですが、画面からの入力自体は何文字でも入力でき、入力確定後の画面では入力した文字がすべて表示されていますが、再表示すると30文字までしか保存されていません。これは仕様なのでしょうか。入力確定時にもエラーにならないため、切り捨てられて登録されていることに気づかないです。他のカラムも長さチェック、エラーメッセージ表示はなく、登録時に切り捨てられているようです。

**Comment by junmt** [comment]
回答が遅くなりまして大変申し訳ございません。
こちらは今のところ仕様になります。

入力チェックは検討しておりますが、各項目の文字数の定義がDBに保存されておらず、マイグレーションなどの観点も含めると中々手を付けることができていない状況です。

**Comment by hiroshih** [comment]
ご回答ありがとうございます。
仕様とのこと承知いたしました。運用で気を付けるようにしたいと思います。
