### ISSUE TITLE
[不具合]Webフォーム作成時にモジュールが選択できない

### ISSUE THREAD

**Issue by suzuki-y2** [thinkingreed-inc/F-RevoCRM#858]
**概要（Overview）**
Webフォームのモジュールのプルダウン項目を選択してもモジュール名が表示されない。
検索しても同様でモジュール名は表示されない。

**再現手順（To Reproduce）**

1. 設定＞システム設定
1. 自動化＞Webフォーム
1. Webフォームの追加
1. モジュールを選択

**スクリーンショット（Screenshots）**
![image](https://github.com/thinkingreed-inc/F-RevoCRM/assets/108853236/9f9f2de5-4df8-4cbb-ba4b-c980ca7bd8cd)

**Comment by junmt** [comment]
不具合のご報告ありがとうございます。
私の手元に修正されたものがあったので、margeまで実施しております。
最新のソースコードで再度お試しいただければ幸いです。
