### ISSUE TITLE
[不具合] Web フォーム作成後エラーが表示される

### ISSUE THREAD

**Issue by tsutosan** [thinkingreed-inc/F-RevoCRM#868]
**概要（Overview）**
不具合の内容を簡潔に記載してください。
（A clear and concise description of what the bug is.）
Web フォームを作成後、不完全な画面が表示される。
ソースを確認するとエラーが出ている。

**再現手順（To Reproduce）**
不具合の発生手順を細かく記載してください。
（Steps to reproduce the behavior:）
1.設定→システム設定→自動化→Web フォームと遷移
2. 「＋Webフォームの追加」ボタンを押下し、何らかの Web フォームを作成する
3. 不完全な画面が表示される
　既に作成されたフォームを一覧画面でクリックしても同様の状態となる。

**スクリーンショット（Screenshots）**
スクリーンショットがあれば添付してください。
（If applicable, add screenshots to help explain your problem.）
![image](https://github.com/thinkingreed-inc/F-RevoCRM/assets/77785639/571b2c13-4cda-45e3-9376-73bc25e4f220)

**稼働環境 Server (please complate the following information):**
- OS: Ubuntu Server 22.04LTS
- PHP version : PHP 7.4.33
- MySQL version: 8.0.34-0ubuntu0.22.04.1 for Linux on x86_64

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: Windows11
- Browser: Google chrome 
- Version: 116.0.5845.111（Official Build） （64 ビット）

**その他情報（Additional context）**

**Comment by junmt** [comment]
github版の話ではないのでクローズ。
