### ISSUE TITLE
[不具合]子コメントのついた親コメントを削除すると、コメント件数がおかしくなる

### ISSUE THREAD

**Issue by hasesho28** [thinkingreed-inc/F-RevoCRM#893]
**概要（Overview）**
掲題の通り。

**再現手順（To Reproduce）**
1. 子コメントがついたコメントの親コメントを「削除」する

**スクリーンショット（Screenshots）**
![image](https://github.com/thinkingreed-inc/F-RevoCRM/assets/84055994/1bdf083d-f88f-48ed-82ed-8cf5ccf1e7d2)
　　↓
「親コメントです」を削除
　　↓
![image](https://github.com/thinkingreed-inc/F-RevoCRM/assets/84055994/c8210ee5-944a-4ec7-bb12-7c59c8084c38)

**その他情報（Additional context）**
恐らく子コメントのみが裏で生き残っていて、コメントとしては表示されないがカウントを取得しているクエリが親コメントの削除を考慮していない

**Comment by junmt** [comment]
fork_from_hereの以下のファイルを参考に修正してください。
modules/ModComments/models/Record.php

**Comment by K-Haruto** [comment]
@junmt 
fork_from_hereの内容を元に修正を行いました。

過去に親コメントが削除されている子コメントについては、
7.4.0のマイグレーションにて削除されるようにしました(fork_from_hereには未反映)。
