### ISSUE TITLE
[要望] Webフォーム参照フィールドを「cf_xxx」の形で表示してほしい

### ISSUE THREAD

**Issue by gatty2672** [thinkingreed-inc/F-RevoCRM#91]
**要望とその背景（Request and its background）**
カスタムフィールド(画面から作成した項目)をWebフォームで選択した際に「ラベル：項目名」の形式で表示されるが、
「フォームを表示する」で確認すると、カスタムフィールドのname属性が「cf_xxx」(xxxは数字)となっているため、
Webフォーム参照フィールドに「cf_xxx」の形式で表示してほしいです。

**その他情報（Additional context）**

「Webフォームの詳細画面」
![#91_1](https://user-images.githubusercontent.com/77664240/111965900-9ee2ea00-8b39-11eb-928b-7c753aac3772.png)

「フォームを表示する」
![#91_2](https://user-images.githubusercontent.com/77664240/111966114-e4071c00-8b39-11eb-94c9-900584dbdad7.png)

**Comment by Remicck** [comment]
カスタムフィールドの場合も、cf_1046などのfieldnameを使って値をPOSTするため、この画面でも確かにそちらの値が出ていたほうがいいように感じます。

報告ありがとうございました。
