### ISSUE TITLE
[質問]初心者用の利用ガイドについて

### ISSUE THREAD

**Issue by kirachki** [thinkingreed-inc/F-RevoCRM#953]
**質問内容（Contents of question）**
ワークフロー機能、ダッシュボード機能を使いこなしたいのですが、ベースナレッジがないのでほとんど使えていません。

OSSユーザでもアクセス可能な資料はございませんでしょうか？

**Comment by Remicck** [comment]
@kirachki 
おまたせしておりすみません。
ご要望をよくいただくため、現在作成中となります。
時期等明言できないのですが、数ヶ月以内には出したいと思っていますので少々お待ちください。
