### ISSUE TITLE
ワークフローにアクションを追加するときのカスタム関数について

### ISSUE THREAD

**Issue by kirachki** [thinkingreed-inc/F-RevoCRM#955]
**質問内容（Contents of question）**
ワークフローにアクションを追加するときの選択肢として、カスタム関数というものがあるのですが、
１．標準で用意されているものでしょうか？
２．それとも、自分達で作成するものであれば、どのように作成するかをご教示ください。

**Comment by junmt** [comment]
自分で作成する必要があります。
作成方法は以下のようなVtigerのカスタム関数の作成方法を参考にしてみてください。
https://discussions.vtiger.com/discussion/192749/workflow-invoke-custom-function
