### ISSUE TITLE
[要望]ワークフローなどでメール通知をしたものが、顧客企業モジュールの「概要」タブ活動の欄で HTMLタグが表示されるのでタグを除外してほしい。

### ISSUE THREAD

**Issue by tsutosan** [thinkingreed-inc/F-RevoCRM#963]
**要望とその背景（Request and its background）**
ワークフローなどで送付したメールが、関連付けられている顧客企業モジュールの「概要」タブに表示されるが、
その際、HTMLタグが表示される。
タグを除外するか、レンダリングして表示するようにしてほしい。

**Comment by junmt** [comment]
strip_tagsでタグを取り除く。
そのまま表示するとHTMLが崩れる。
