### ISSUE TITLE
[不具合]役割が下位のユーザーが作成した共有されていないリストが上位のユーザーにすべて表示される

### ISSUE THREAD

**Issue by tsutosan** [thinkingreed-inc/F-RevoCRM#964]
**概要（Overview）**
「役割」が上位のユーザーには、下位のユーザーが作成したリストすべてが表示される。

**再現手順（To Reproduce）**
1. 役割「パートアルバイト」のユーザー A を作成する。
2. A でログインし、どのモジュールでも構わないのでリストを作成する。この際共有はしない。
3. 役割「マネージャー」のユーザー B を作成する。
4. B でログインし、2 で作成したモジュールの一覧表示に遷移する。
5. 2 で作成した共有設定していないリストが表示されている。

**稼働環境 Server (please complate the following information):**
- OS: [e.g. CentOS8]
- PHP version [e.g. PHP 7.4.11]
- MySQL version [e.g. MySQL 8.0.21]

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
OS: Windows11
Browser : Chrome
Version 120.0.6099.71（Official Build） （64 ビット）

**Comment by junmt** [comment]
config.customize.phpの
$show_subordinate_roles_list = true;// trueの場合：共有リスト欄に下位の役割が作成した全てのリストを表示。
をfalseに変更してください。
