### ISSUE TITLE
[質問]APサーバのチューニングパラメータについて

### ISSUE THREAD

**Issue by kirachki** [thinkingreed-inc/F-RevoCRM#965]
**質問内容（Contents of question）**
MySQLはバッファキャッシュサイズの見直しなどで性能改善しました。

同様にF-RevoCRMのAP観点でApacheのチューニングしたいので、そのポイントを教えて頂けないでしょうか。

**Comment by junmt** [comment]
phpのopcacheを入れておく程度で、デフォルトのままでそれほどパフォーマンスに関わる点はないかと思います。
もしあるならば、https://httpd.apache.org/docs/2.4/ja/mod/prefork.htmlの設定値を変えるか、php-fpmを入れるか、程度かと思います。
要するにPHPのファイルのディスクリードを減らすこと、プロセスの上限を超えて待ち行列が発生しないことを気にする程度かと思います。
