### ISSUE TITLE
[要望]非公開のカレンダーを役割の階層に関係なく非表示にできるようにしてほしい

### ISSUE THREAD

**Issue by tsutosan** [thinkingreed-inc/F-RevoCRM#975]
カレンダーを非公開にした場合、予定ありと表示されるが上位階層のユーザーからは見えてしまう。
プライベートの予定を入力したいとの要望があるので非公開にした場合個人以外からは詳細を見れないようにする機能を実装してほしい。

**Comment by junmt** [comment]
管理者権限がONのユーザーあるいはプロファイルで全て表示になっているため、非公開のデータが見えてしまっているものと思われる。
仕様通りの挙動のため、修正はしない。

![image](https://github.com/thinkingreed-inc/F-RevoCRM/assets/12598156/ed4ca006-edac-45fd-bde9-bdb3595b3be8)
