### ISSUE TITLE
[不具合]リードの電話番号（予備）の形式がメールアドレス

### ISSUE THREAD

**Issue by ratorin** [thinkingreed-inc/F-RevoCRM#980]
**概要（Overview）**
リード昇格マッピングを編集していると、電話番号（予備）の形式がメールアドレスになっていることに気づいた。
おそらく、メールアドレス（予備）の間違いではないかと推察される。

**スクリーンショット（Screenshots）**
![電話番号がメールアドレス](https://github.com/thinkingreed-inc/F-RevoCRM/assets/16488860/8b7319f7-2128-45f6-ae0a-22f20adb4e74)

**Comment by junmt** [comment]
内部名称がsecondaryemailなので仰る通りですね。

**Comment by junmt** [comment]
メモ：マイグレーションスクリプトの中でuitypeを変更する対応を行う。
